Added power law mass ratio distribution
TeamCOMPAS/COMPAS pull request #1028
Opened 2023-12-14 01:33 UTC by SimonStevenson

I have added the possibility of using a power law mass ratio distribution (I had to add it for a project I'm working on).

This is a fairly small PR.

I've attached a plot comparing samples drawn with this new distribution (for a power law exponent of -2) to the theoretical pdf.

![power_law_mass_ratio_dist](https://github.com/TeamCOMPAS/COMPAS/assets/6952112/b01ec3c0-bc09-4ada-8731-fbd4a24f0c79)

I think I've updated the changelog and docs, but please let me know if I missed somewhere.

2023-12-14 09:10 UTC, avigna requested changes
Looks good to me, just an extremely minor comment. Two questions:
1. The plot was produced with COMPAS, right?
2. The power law exponent is user defined and can go from -inf to int, right?

2023-12-14 09:10 UTC, avigna commented on online-docs/pages/whats-new.rst
> +* Added power law mass ratio distribution (``--mass-ratio-distribution POWERLAW```) and associated option (``--mass-ratio-power```)
There are some extra commas here, right? I know its a comment, but just to be clean.

2023-12-14 09:12 UTC, avigna commented
I have reviewed this and effectively approved it (modulo a tiny edit). However, and besides this PR... wasn't the plan to eventually move sampling outside of the src code? Or is the plan to have hibrid version (use COMPAS sampling options vs create your own grids)?

2023-12-14 17:34 UTC, ilyamandel requested changes
I fixed a couple of comment typos directly.

I agree with @avigna that we shouldn't add and maintain any more initial condition distributions -- can do this via grid files -- but since this option already exists, it's fine.

However, given the appearance of a new option, a new default .yaml file should be re-generated (this can be done automagically by running COMPAS).

2023-12-14 19:32 UTC, jeffriley requested changes
Thanks Simon!

In addition to the comments made by @avigna and @ilyamandel : 

Code: 
   - The new option should be included in the `m_BSEOnly` vector in Options.h (see point 10 at the top of Options.cpp)
   - yaml.h needs to be updated to include the new option (see point 13 at the top of Options.cpp)
   - Do we need to sanity check the value entered for `--mass-ratio-power` (are there any values that are not allowed)?
 
Documentation: 

   - Point to the `--mass-ratio-power` option in the description of the available values for the `--mass-ratio-distribution` option (add text something like ("via the --mass-ratio-power option")
   - Make clear in the description of the `--mass-ratio-power` option that it refers only to the `--mass-ratio-distribution` option.

2023-12-14 19:50 UTC, ilyamandel commented
Oh, one more thought: perhaps clarify in the documentation that the power law option uses ``--mass-ratio-min`` and ``--mass-ratio-max`` in addition to the power law slope to determine the distribution.

2024-01-26 20:20 UTC, ilyamandel commented
@SimonStevenson -- ping on this one.

2024-04-13 07:33 UTC, ilyamandel commented
@SimonStevenson -- another ping on this one.

2024-04-25 05:32 UTC, ilyamandel commented
@SimonStevenson , the longer you wait, the more effort it will be to roll this in, as the code keeps evolving... ;-)

2024-04-25 07:21 UTC, closed without merging