Winds patch 3
TeamCOMPAS/COMPAS pull request #1214
Opened 2024-09-05 17:09 UTC by jmerritt1

Related to [Issue #1209 ](https://github.com/TeamCOMPAS/COMPAS/issues/1209#issuecomment-2322775456) we set mass loss to 0 in Remnants.h, and set the Dominant mass loss rate tag to `NONE` for both Belczynski2010 and Merritt2024.

Previously, WD experienced WR mass loss. AGB/post-AGB still experience either GB, MS, or WR winds, depending on mass and radial change fraction settings and initial mass.

2024-09-05 17:26 UTC, jeffriley requested changes
Thanks JD.  Looks good - just a question and a request:

(1) Since the call to `CalculateMassLossRateHurley()` in `Remnants.h` sets mass loss to 0,0, should we also set `m_DominantMassLossRate = MASS_LOSS_TYPE::NONE` there?

(2) Can you update the online documentation for dominant mass loss rate to reflect the current values?  (In `standard-logfiles-record-specification-stellar.rst` (under "COMPAS output"))

2024-09-05 17:39 UTC, jmerritt1 commented
Thanks Jeff, let me know if this looks good.

2024-09-05 17:41 UTC, jeffriley approved these changes
Looks good - thanks JD.

I'll approve - up to @ilyamandel now.

2024-09-06 08:05 UTC, ilyamandel approved these changes
Looks good, thank you, @jmerritt1 !

2024-09-06 08:05 UTC, merged