Default files cleanup
TeamCOMPAS/COMPAS pull request #406
Opened 2020-10-21 06:27 UTC by reinhold-willcox

Removed '_default' extension from default files - it is obvious from the directory. Also fixed some of the default values in stroopwafelInterface to be more realistic.

I did not touch default values in pythonSubmit (noting because this was discussed recently).

2020-10-21 08:24 UTC, ilyamandel requested changes
Are the online and latex documentation properly updated?  E.g., I see references to  pythonSubmitDefault.py in getting_started.md .

2020-10-21 21:22 UTC, reinhold-willcox commented
Ah true, I need to go fix those up.

2020-10-21 21:51 UTC, reinhold-willcox commented
Fixed up the docs. The changelog will conflict with the other PR (or vice versa depending on which gets approved first) but that's an easy fix.

2020-10-22 05:39 UTC, ilyamandel approved these changes

2020-10-22 05:40 UTC, merged