Make sure Case C mass transfer is labelled as Case C not Case B
TeamCOMPAS/COMPAS pull request #484
Opened 2020-12-14 18:34 UTC by TomWagg

This addresses one of the problems in #483 but probably not all. I moved the DetermineMassTransferCase definition from GiantBranch.h to CHeB.h so that stellar types 4+ are labelled as case C (previously HG took priority and everything 2+ got labelled case B).

Additionally, why are HeMS and HeHG labelled as case A and B, Lieke and I had assumed those should also just be case C?

2020-12-14 19:13 UTC, jeffriley requested changes
Though moving the DetermineMassTransferCase() function from GiantBranch to CHeB will achieve the desired result in this case, it is not the correct long-term solution.

The correct solution is to leave the DetermineMassTransferCase() function in GiantBranch unchanged, and add a DetermineMassTransferCase() function to CHeB.h that calls the GiantBranch function.  So reinstate the GiantBranch function and change your CHeB function to:

MT_CASE         DetermineMassTransferCase()                                  { return GiantBranch::DetermineMassTransferCase(); }

So it skips over HG in the inheritance chain.

I think this is just another case that indicates HG probably shouldn't inherit from GiantBranch.  The main reason it does is that HG uses the GBParams.  Maybe we can fix that one day.

2020-12-14 19:20 UTC, jeffriley commented
>  why are HeMS and HeHG labelled as case A and B, Lieke and I had assumed those should also just be case C?

That you'll have to take up with @SimonStevenson, @avigna, or @ilyamandel.  Here is the function from the legacy code:

    int massTransferCase(int stellarType){
	    // Function to determine if the star which initiated mass transfer will go through case A, B or C.
        if(stellarType == MS_MORE_THAN_07 or stellarType == MS_LESS_THAN_07 or stellarType == NAKED_HELIUM_STAR_MS){
            return CASE_A;
        }
        else if(stellarType == HERTZSPRUNG_GAP or stellarType == NAKED_HELIUM_STAR_HETZSPRUNG_GAP){
            return CASE_B;
        }
        else if((stellarType >= FIRST_GIANT_BRANCH and stellarType <= THERMALLY_PULSING_ASYMPTOTIC_GIANT_BRANCH) or NAKED_HELIUM_STAR_GIANT_BRANCH){
            return CASE_C;
        }
        else{
            return NO_MASS_TRANSFER;
        }
    }

It looks to me that HeMS is CASE_A because it is treated as a MS star, and similarly HeHG is treated as a HG star - but someone with a better understanding might need to explain why :-)

2020-12-14 19:32 UTC, TomWagg commented
Ah okay, I've changed it to do what you said now @jeffriley. For future reference, why is this the correct solution? Does there always need to be a definition in GiantBranch.h?

And I see, good to know, definitely intrigued to hear from the others why this is the case :)

2020-12-14 19:34 UTC, jeffriley commented
And based on the legacy function (now that I understand better what is going on...), we probably should change the DetermineMassTransferCase() functions for all stellar types to actually inherit rather than just set the mass transfer case.

From the legacy function the inheritance should be:

    MainSequence sets CASE_A
        MS_lte_07 inherits from MainSequence, so needs no DetermineMassTransferCase() function
        MS_gt_07 inherits from MainSequence, so needs no DetermineMassTransferCase() function
        HeMS inherits from TPAGB , so needs a DetermineMassTransferCase() function that calls MainSequence ::DetermineMassTransferCase()

    GiantBranch sets CASE_C
        FGB inherits from HG, so needs a , so needs a DetermineMassTransferCase() function that calls GiantBranch::DetermineMassTransferCase()
        CHeB inherits from FGB , so needs no DetermineMassTransferCase() function
        HeGB inherits from HeHG, so needs a DetermineMassTransferCase() function that calls GiantBranch::DetermineMassTransferCase()

    HG sets CASE_B
        HeHG inherits from HeMS, so needs a DetermineMassTransferCase() function that calls HG::DetermineMassTransferCase()


*Unless* we just want to set the mass transfer case for each stellar type individually, and not use inheritance for mass transfer case (e.g. envelope type - I think we set envelope type for each stellar type individually - we don't use inheritance)

2020-12-14 19:36 UTC, jeffriley commented
> For future reference, why is this the correct solution? 

It's the correct solution if we want to use inheritance to set mass transfer case.  If someone adds a new stellar type (as we did with CH) then they may be expecting to be able to inherit from GiantBranch.  If we don't want to use inheritance then we should just se the mass transfer case for each stellar type individually - but even then you'd probably want to fallback to the inheritance chain if someone forgot...

2020-12-14 19:45 UTC, TomWagg commented
Thanks for explaining Jeff :)

I am happy to change the functions to do as you say above. I just want to check this is the definition of mass transfer cases that everyone uses or at least understand why it is different from what I expect. I'm still new to all of this but I had learnt from the Pols notes ([See 6.2.3](https://www.astro.ru.nl/~onnop/education/binaries_utrecht_notes/Binaries_ch6-8.pdf)) that they are defined

- Case A: A binary that fills its Roche lobe for the first time as it expands on the main sequence
- Case B: A binary that fills its Roche lobe for the first time as it expands after hydrogen exhaustion
- Case C: A binary that fills its Roche lobe for the first time as it expands after helium exhaustion

Which I had always interpreted as A=MS-HG, B=HG-CHeB, C=Else. I realise that Pols notes can sometimes be out of date so perhaps these definitions are more exact now?

2020-12-14 19:52 UTC, jeffriley commented
> I just want to check this is the definition of mass transfer cases that everyone uses 

I'll leave that to others to answer - actually I think there was a discussion in slack somewhere about this recently.  From memory there may not be consensus on the definitions (I think @demink was involved in that discussion).

2020-12-14 19:58 UTC, TomWagg commented
Ah yeah I see you're right, @reinhold-willcox has already had these same questions [here](https://compashq.slack.com/archives/CMCEQ0RS8/p1603847418103500) :D

Based on that thread it seems that this variable going to become obsolete anyway so probably not worth worrying about this all too much

2020-12-14 20:02 UTC, jeffriley commented
Oh, and HeWD should set NONE - and the the other remnants inherit from that

2020-12-14 20:50 UTC, jeffriley commented
> Based on that thread it seems that this variable going to become obsolete anyway so probably not worth worrying about this all too much

Possibly not, but until it becomes obsolete we should probably make the code consistent with legacy.  You can do that with this PR if you want, or I can do it later - whatever works for you.

2020-12-14 22:13 UTC, TomWagg commented
Yes very fair! I think this latest commit should follow what you said above?

2020-12-14 22:21 UTC, ilyamandel commented
@TomWagg -- why do we need this functionality at all? :)  Seriously, I'd prefer to get rid of it.  We have functionality for recording the evolutionary stages of the donor and accretor in every mass transfer episode.  This allows the user to determine for themselves what the type of MT was, rather than debating the type of MT that should be associated with, say, a HeMS donor (I would call it case B, for what my opinion is worth, but that's not the point).

2020-12-14 22:46 UTC, jeffriley commented
@ilyamandel @TomWagg Happy for the functionality to come out now (since, as Ilya says, we have the history now), but if we're not going to pull it out now we should at least make it not wrong.

2020-12-14 23:14 UTC, TomWagg commented
Yes completely agree Ilya, did Reinhold already implement the MT history array as you mentioned in the slack thread? If so I figure we can just remove all of this mass transfer case stuff.

If not, I agree with Jeff that we might as well merge these fixes in the meantime for anyone currently using the code (e.g. Lieke and I didn't realise the MT_CASE stuff was off and were trying to analyse things based on it)

2020-12-14 23:19 UTC, jeffriley commented
> did Reinhold already implement the MT history array

Yes, in v02.17.01.  Look for MT_DONOR_HITS in the documentation

2020-12-15 04:43 UTC, TomWagg commented
Ah nice, that looks awesome! In that case, I would vote we just remove this other mass transfer stuff as it can just be confusing and the history has all of the information.

2020-12-15 08:04 UTC, reinhold-willcox commented
Just catching up on all these comments - yes the MassTransferDonorHist variable is working, though it doesn't include information about the Accretor (which may or may not be useful, depending on how you interpret the "secondary" in Lieke's plots above). 

Also, note that it gives just the stellar types of the donor, so you have the freedom to choose which definition of the Mass Transfer Case to use.

2020-12-15 10:21 UTC, avigna commented
> Just catching up on all these comments - yes the MassTransferDonorHist variable is working, though it doesn't include information about the Accretor (which may or may not be useful, depending on how you interpret the "secondary" in Lieke's plots above).

I'd say accretor is important.

> Also, note that it gives just the stellar types of the donor, so you have the freedom to choose which definition of the Mass Transfer Case to use.

Agreed.

2020-12-15 21:10 UTC, jeffriley commented
Ok, so what's the consensus?  Do we leave this functionality in (and fix it), or doe we take it out?

2020-12-16 22:43 UTC, ilyamandel commented
I vote for getting rid of the MT case functionality (and yes, I agree we should actually get rid of it, not just keep something that's wrong).

2020-12-17 16:01 UTC, closed without merging