Fix for neutrino mass loss during BH formation Issue #453
TeamCOMPAS/COMPAS pull request #515
Opened 2021-01-20 00:00 UTC by SimonStevenson

Fix for neutrino mass loss during BH formation Issue #453 details in the issue

2021-01-20 02:35 UTC, SimonStevenson commented
(I know that I need to update the changelog + version number, but will wait until people are happy with the changes and then we can add those in)

2021-01-21 05:43 UTC, reinhold-willcox commented
Leaving to @avigna who I think already has tests prepared for this.

2021-01-21 06:49 UTC, ilyamandel commented
Two questions:
- Should we consider changing the pythonSubmit default to NEUTRINO_MASS_LOSS_PRESCRIPTION::FIXED_MASS rather than FIXED_FRACTION, with 0.1 solar masses of mass loss?
- Should we change the default behaviour in  BH::CalculateNeutrinoMassLoss_Static() when the mass loss prescription is unknown to gravitationalMass = p_BaryonicMass rather than gravitationalMass = 0?

2021-01-21 21:02 UTC, avigna commented
Thanks for the questions Ilya. I don't feel strongly about the first one, if we have a reference for that lets make it the default. The second one I strongly suggest we do it, will add it to the review (as well as changing the log and version number).

2021-01-21 23:13 UTC, ilyamandel commented
@avigna : For a reference, see footnote 7 in Stevenson+, 2019, courtesy of Bernhard Mueller: 
https://ui.adsabs.harvard.edu/abs/2019ApJ...882..121S

2021-01-21 23:49 UTC, avigna commented on defaults/pythonSubmit.py
> +    neutrino_mass_loss_BH_formation = "FIXED_FRACTION"          # "FIXED_MASS"
Ilya suggest to change to FIXED_MASS.

2021-01-21 23:49 UTC, avigna commented on defaults/pythonSubmit.py
> +    neutrino_mass_loss_BH_formation_value = 0.1                 # Either fraction or mass (Msol) to lose
Ilya suggest to change to 0.1 solar masses of mass loss.

2021-01-22 00:11 UTC, avigna requested changes
In file src/GiantBranch.cpp in line 1472 add "gravitationalMass = p_BaryonicMass" for default/unknown SN engine (see Ilya's comment on that on the conversation).
Update changelog and version number.
After that, good to go.

2021-01-31 23:22 UTC, SimonStevenson commented
I've incorporated the requested changes @avigna . Sorry it took me a while to get around to it!

2021-02-01 02:41 UTC, avigna approved these changes
All good! Thanks Simon!

2021-02-01 02:41 UTC, merged