Missing mergers fix
TeamCOMPAS/COMPAS pull request #784
Opened 2022-04-11 05:08 UTC by reinhold-willcox

Possible fix for issue #783 , in which some mergers between BHs and massive stars do not show up in `BSE_RLOF`. 

Based on the system I posted in that issue, I found that in the final evolution step (for BH+HG binary), within `EvaluateBinary`:
- CalculateMassTransfer determined there was no RLOF and nothing to do
- CalculateWindsMassLoss was removing a small amount of wind from the HG
- It was not a CE or stellar merger, and no SN was occuring, so the code entered the 'else' clause followed by `ResolveMassChanges`
- Here, the binary angular momentum changes s.t the components are now touching, hence m_Flags.stellarMerger is set to true. Then `EvaluateBinary` finishes and returns to `Evolve` where the next call is to `PrintRLOFParameters` which should be resulting in `BSE_RLOF` output. 

However, `PrintRLOFParameters` only logs RLOF Parameters if either star `IsRLOF()`, but by going through ResolveMassChanges, neither star has this set. To set it, the stars must have had `m_StarX->InitialiseMassTransfer()` called (which occurs when `CalculateMassTransfer()` leads to touching, but not when `ResolveMassChanges()` does). 

To fix this, I've added the lines:
```
m_Star1->InitialiseMassTransfer(m_CEDetails.CEEnow, m_SemiMajorAxis, m_Eccentricity);
m_Star2->InitialiseMassTransfer(m_CEDetails.CEEnow, m_SemiMajorAxis, m_Eccentricity); 
```
immediately below `m_Flags.stellarMerger = true;` when the stars are found to be touching following ResolveMassChanges. 

I can verify that this logs the merger in `BSE_RLOF` correctly and thus fixes the issue, but I am not sure that this is necessarily the best way to accomplish this and avoids introducing other complications, so I defer to @jeffriley 's judgement.

2022-04-11 06:25 UTC, jeffriley commented
I haven't checked, but I would guess that calling 

    m_Star1->InitialiseMassTransfer(m_CEDetails.CEEnow, m_SemiMajorAxis, m_Eccentricity);
    m_Star2->InitialiseMassTransfer(m_CEDetails.CEEnow, m_SemiMajorAxis, m_Eccentricity);

causes the entries to be recorded in  BSE_RLOF because BinaryConstituentStar::InitialiseMassTransfer() calls BinaryConstituentStar::SetRocheLobeFlags(), so sets the RLOF flags correctly for the HG star after the winds mass loss.  The only other thing that BinaryConstituentStar::InitialiseMassTransfer() does is set m_MassTransferDiff = 0.0, which is probably superfluous, but also probably not harmful in this case.

So perhaps just calling 

    m_Star1->SetRocheLobeFlags(m_CEDetails.CEEnow, m_SemiMajorAxis, m_Eccentricity);
    m_Star2->SetRocheLobeFlags(m_CEDetails.CEEnow, m_SemiMajorAxis, m_Eccentricity);

is cleaner.

2022-04-11 21:21 UTC, ilyamandel commented
How does the star go from no RLOF to touching if all that happened in between was a small amount of mass loss through winds?

2022-04-11 22:08 UTC, jeffriley commented
> How does the binary go from no RLOF to touching if all that happened in between was a small amount of mass loss through winds?

I don't know how much mass was lost - I assume enough to change the radius to turn the RLOF flag on... It must be on after the mass loss, othwerwise @reinhold-willcox's changes wouldn't have fixed the problem.  Maybe @reinhold-willcox can answer that.

2022-04-12 03:18 UTC, jeffriley requested changes
Needs changelog and version updates.

Also needs some more investigation before applying this fix - see questions/comments above.

2022-04-12 05:09 UTC, reinhold-willcox commented
@ilyamandel By peppering `EvaluateBinary` with std::cout lines, I think I've found the answer. The commented values below are the relevant attributes when printed at that location. The change occurs only after ResolveMassChanges(). What seems to be happening is that, although the timestep is fairly small and the mass loss is minimal, ResolveMassChanges triggers a change in stellar type of the secondary from HG to CHeB, which apparently leads to a huge jump in radius, from 150 to 2000 Rsun, leaping over the 1000 Rsun separation. 
 
@jeffriley You are correct though, the mass loss does in fact widen the binary by a bit, but not nearly enough to offset the radius jump.

 ```
 void BaseBinaryStar::EvaluateBinary(const double p_Dt) {
 
    //p_Dt = 5.74378e-05
 
    //PreMT
    //M1   = 12.8231
    //M2   = 57.1315
    //R1   = 5.43698e-05
    //R2   = 151.701
    //a_Ro = 949.682
    //St1  = Black_Hole
    //St2  = Hertzsprung_Gap
 
    CalculateMassTransfer(p_Dt);
 
    //Between MT and winds
    //M1   = 12.8231
    //M2   = 57.1315
    //R1   = 5.43698e-05
    //R2   = 151.701
    //a_Ro = 949.682
    //St1  = Black_Hole
    //St2  = Hertzsprung_Gap
 
    CalculateWindsMassLoss();
 
    //PostWinds
    //M1   = 12.8231
    //M2   = 57.1315
    //R1   = 5.43698e-05
    //R2   = 151.701
    //a_Ro = 949.682
    //St1  = Black_Hole
    //St2  = Hertzsprung_Gap
 
    if (...some stuff that doesn't matter here...)
    else {
        ResolveMassChanges();
 
        //PostResolveMassChanges
        //M1   = 12.8231
        //M2   = 56.5602
        //R1   = 5.43698e-05
        //R2   = 2176.41
        //a_Ro = 957.567
        //St1  = Black_Hole
        //St2  = Core_Helium_Burning
 
 
        if (HasStarsTouching()) {
            m_Flags.stellarMerger = true;
                                                                                                                                                                                                                                                                                
        }                                                                                                                                                                                                                                                                       
    }                                                                                                                                                                                                                                                                           
```

2022-04-12 10:48 UTC, jeffriley approved these changes
All good @reinhold-willcox - I changed some comments around the calls to SetRocheLobeFlags()

2022-04-12 10:48 UTC, merged

2022-04-18 00:28 UTC, reinhold-willcox commented
Meant to add previously, this partially resolves #774