minor changes in stroopwafelinterface to work with runSubmit
TeamCOMPAS/COMPAS pull request #789
Opened 2022-04-21 16:25 UTC by LiekeVanSon

Resolving issues raised in #741 .

Stroopwafel now runs without an error. MC only runs properly.
Full AIS needs to be tested more thoroughly

2022-04-26 07:26 UTC, avigna requested changes
Address changes in comments.

2022-04-26 07:26 UTC, avigna commented on utils/preProcessing/stroopwafelInterface.py
>      # Over-ride with pythonSubmit parameters, if desired
Change this comment to:
Over-ride with runSubmit + compasConfigDefault parameters, if desired

Same in line 22 of this file, where the comment "Include options from local pythonSubmit file" should be "Include options from local runSubmit + compasConfigDefault files".

2022-04-26 07:39 UTC, avigna commented
On the side: closing this issue *might* help with #753

2022-04-27 13:51 UTC, avigna approved these changes

2022-04-27 13:51 UTC, merged

2022-05-24 20:59 UTC, stellarphysicsandpopulations commented
(Stephen) 
Lieke's fix worked great for me, except that I needed to pass the full path to the YAML file to runSubmit, even though it's the same directory as my runSubmit:

##### programOptions = pythonProgramOptions()
##### the above doesn't work, somehow... I needed to pass the explicit location of the yaml file, so:
yaml_file_location = os.path.join(path_to_runSubmit, 'compasConfigDefault.yaml')
programOptions = pythonProgramOptions(config_file=yaml_file_location)

I don't know why. I suspect this is *not* because of the changes in the Stroopwafel version I'm using. I guess it's because I'm using the Docker version of COMPAS?  (Or maybe my installation is also somehow weird in a different way...)

(So far I'm hard-coding an assumption about the name of the file, and that it is in the same location as runSubmit.py, but that can be changed.)

(Tagging @FloorBroekgaarden too, in case this saves time for others.)

2022-05-24 20:59 UTC, stellarphysicsandpopulations commented
(Stephen) 
Lieke's fix worked great for me, except that I needed to pass the full path to the YAML file to runSubmit, even though it's the same directory as my runSubmit:

##### programOptions = pythonProgramOptions()
##### the above doesn't work, somehow... I needed to pass the explicit location of the yaml file, so:
yaml_file_location = os.path.join(path_to_runSubmit, 'compasConfigDefault.yaml')
programOptions = pythonProgramOptions(config_file=yaml_file_location)

I don't know why. I suspect this is *not* because of the changes in the Stroopwafel version I'm using. I guess it's because I'm using the Docker version of COMPAS?  (Or maybe my installation is also somehow weird in a different way...)

(So far I'm hard-coding an assumption about the name of the file, and that it is in the same location as runSubmit.py, but that can be changed.)

(Tagging @FloorBroekgaarden too, in case this saves time for others.)

2022-05-24 22:06 UTC, stellarphysicsandpopulations commented
Thinking more clearly, it can't be anything to do with me using the Docker version, at least not directly... this setup is well before we get to the Docker call.  Interesting.  Oh well, it was fun to investigate, whatever the reason.

2022-05-25 06:38 UTC, avigna commented
What sort of error do you get, Stephen?

2022-05-25 07:21 UTC, stellarphysicsandpopulations commented
With the fix above, no error.  If I don't pass the full path to the YAML file then runSubmit somehow doesn't find the YAML file (even though it's in the same directory).   

Not an issue for me, now.  Whether it's important or not for other depends on how weird my case it.