Accretion onto WhiteDwarfs
TeamCOMPAS/COMPAS pull request #822
Opened 2022-06-24 02:26 UTC by solfreludio

This should fix the remaining extremely-massive HeWDs, as well as include rejuvenation of HeWDs (into HeMS), evolution of COWDs into ONeWDs, double detonations for COWDs and Sub-Chandrasekhar SN for HeWDs. 

I opened a draft pull request as I'm 99% sure that my implementation of the SN events is incomplete, but I have left boolean "flags" that point towards when a SN should happen (`m_SubChandrasekhar` and `m_DoubleDetonation`). 

I tried to follow the suggested programming style, I hope the code is clear enough.

2022-06-26 17:18 UTC, ilyamandel requested changes
BaseBinaryStar.cpp: 

- why do you need "m_Accretor->SetMassTransferDiff(mdEnvAccreted);" on both lines 1895 and 1912?

- @jeffriley will probably comment in more detail on the code, but AccretionRegime should be a defined type with values like ACCRETION_REGIME::NOVA or whatever, not arbitrary numbers like 10 that do not make sense when reading the code (note that 10 is not even defined in the comments, which only run 0--6);

- should a HeHG or HeGB star be treated as a giant?

- code starting line 1926 seems to almost repeat code starting line 1895; that's generally a bad idea (someone is likely to update code in one lace but not another in future changes, etc.), so it would be better to factor out common pieces of code into a separate function if necessary.

2022-06-26 17:24 UTC, ilyamandel requested changes
BaseStar.h:

- a lot of the internal variables introduced here are only relevant for WDs -- so why do they need to live in BaseStar.h, rather than WD.h or appropriate WD class?

-     double                  m_l0;                                       // Required for accretion limit onto HeWD
    double                  m_lambda;                                   // Required for accretion limit onto HeWD
    double m_X; // Required for accretion limit onto HeWD
    
    The comments should say what the variable stands for; I'd also recommend more descriptive names (e.g., lambda has other meanings in the code where it refers to envelope binding energy).

2022-06-26 17:55 UTC, ilyamandel requested changes
COWD.cpp and elsewhere:

double LogMdot = log10(p_AccretedMass / p_Dt) - 6; // Logarithm of the accreted mass (M_sun/yr)

The choice of the time step Dt may not match the actual duration of the mass transfer phase in COMPAS.  Therefore, it is unsafe to use Dt for determining the mass transfer rate.  We do track the mass transfer rate *and* the amount of mass transferred in BaseBinaryStar.cpp.  These should be used directly, instead of relying on Dt.

2022-06-26 18:06 UTC, ilyamandel requested changes
COWD.cpp:

- I suggest including Log in all logged variable names for consistency;

- m_Mass > 1.3
This should probably be defined somewhere; where does this choice come from?

- If a COWD exceeds the Chandrasekhar mass through slow MT (no off-center ignition), it currently leaves behind a massless remnant -- is that correct?

2022-06-26 18:07 UTC, ilyamandel reviewed
Following up on COWD: 
Is the mass actually updated by the time the accretion regime is resolved?

2022-06-26 18:15 UTC, ilyamandel requested changes
WhiteDwarfs.cpp:

    if (p_IsHeRich) {
        thisMassRate = DonorMassRate * CalculateetaHe(p_LogDonorMassRate);
    } else {
        thisMassRate = DonorMassRate * CalculateetaHe(p_LogDonorMassRate) * CalculateetaH(p_LogDonorMassRate);
    }
    
    - Why is etaHe still used as a term in the MT accretion efficiency for H-rich donors?
    
WhiteDwarfs.h:

- Where do the expressions for l0, X, and lambda come from?

2022-06-26 18:18 UTC, ilyamandel requested changes
constants.h:

constexpr double M_HE_BUR = 0.35; 

- Is this consistent with the Hurley+ SSE choices?  Should we just use those values, since we use them elsewhere in the code?

2022-06-26 18:21 UTC, ilyamandel requested changes
General questions: 

- Do we want to fix the prescriptions / choices for accretion onto WDs, or create options for the user to explore different assumptions?

- Do we want to produce additional outputs letting the users know, e.g., when novae happen and how bright they are?

You will need to update the changelog.h file and also the documentation (if extra input options or  outputs are created).

2022-06-27 09:39 UTC, jeffriley requested changes
First, let me say "good job"!  It's good to see the code being improved by the community.

What follows is not very well-structured, sorry - it's really just a brain dump as I read through the code.

**A suggestion:**

We have these constructs in BaseBinaryStar::CalculateMassTransfer():

    bool accretorIsWD                 = m_Accretor->IsOneOf({ STELLAR_TYPE::HELIUM_WHITE_DWARF, STELLAR_TYPE::CARBON_OXYGEN_WHITE_DWARF, STELLAR_TYPE::OXYGEN_NEON_WHITE_DWARF }); //To confirm that the accretor is a WD
    bool donorIsHeRich                = m_Donor->IsOneOf({ STELLAR_TYPE::NAKED_HELIUM_STAR_MS, STELLAR_TYPE::NAKED_HELIUM_STAR_HERTZSPRUNG_GAP, STELLAR_TYPE::NAKED_HELIUM_STAR_GIANT_BRANCH, STELLAR_TYPE::HELIUM_WHITE_DWARF }); // Check composition of accreted material

I wonder if we should define "convenience" initializer_lists in constants.h for these?  See, for example:

    const std::initializer_list<STELLAR_TYPE> COMPACT_OBJECTS

in constants.h


**In BaseBinaryStar::CalculateMassTransfer():**


- Local variables FractionAccretedMass and AccretionRegime in  - can you change those to begin with lowercase letters?  Note the "Naming conventions" section of the Developer Guide:

https://compas.readthedocs.io/en/latest/pages/Developer%20guide/Programming%20style/programming-style-style-naming.html


**In DetermineAccretionRegime(bool p_HeRich, const double p_AccretedMass, const double p_Dt)**

Why is the first parameter not const?


**In IncrementShell(const double p_AccretedMass, bool p_HeRich)**

Why is the second parameter not const?


**Reiterating @ilyamandel 's comments re variable names:**

    double                  m_l0;                                       // Required for accretion limit onto HeWD
    double                  m_lambda;                                   // Required for accretion limit onto HeWD

It may be so that these are required for accretion limit onto HeWD, but what do they represent? Neither the name nor the description gives me any real clue as to what the variables actually represent.  Back in the day when we were limited to 8 characters for variable names in FORTRAN it was hard to dream up meaningful variable names, but that limit doesn't apply anymore, so we should have variable names that help future readers and maintainers of the code understand what the variable is for.  Longer names help, but not too long (e.g a variable names like 'thisIsAVeryLongVariableNameThatIAmUisingToHelpTheCodeBeMoreUnderstandable' actually hinder readability rather than help, especially if you have several of them in a single line of code).

The aim is to make the code easy to read and understand for someone reading or maintaining it a couple of years from now when the original author may not be around to ask what they meant by "m_l0").

**In COWD::DetermineAccretionRegime():**

- Same comment as above re local variable names - out convention is to (generally) start local variable names with lowercase letters.
- Should we put the constants in constants.h?  We should at least document where they came from.
- I agree with @ilyamandel re the accretion regime.  Rather than hard-coding numbers, look at something like "enum class MASS_TRANSFER" in constants.h and copy that construct and usage - doing it that way is more understandable to readers of the code, more maintainable, and more extensible. (Constants are also used in HeWD::DetermineAccretionRegime()).


**General comment on multiple return statements in a function:**

Unless the function is very short, you really should (generally) have a single entry point, and a single exit point - our convention is rather than have multiple "return" statements sprinkled throughout the function, instead define a variable at the start of the function, set it to a default value, then set it to the return value throughout the function, and return it at the end when the function is exited. The reason for this is that if the function is a long/complex function, readers/maintainers of the code can easily miss a return statement buried in the code somewhere - it's easier to read and understand what the function is doing if you can assume that we start executing the function at the top of the function, and exit it at the bottom.  You can - and we do in places - have a sanity check at the top of the function and exit there if we really shouldn't be there, but other than that, a single entry and a single exit is more readable and easier to maintain.  As I said earlier, if the function is just a single "if" statement and only a few lines of code, you can get away with multiple return statements - because the reader can see them all there in front of them - but more than a few lines of code and you want to move to a single entry and a single exit.

(we do a bit of the sanity-checking-type returns at the start of BaseBinaryStar::CalculateMassTransfer())


**General comment on floating-point comparisons:**

See: https://compas.readthedocs.io/en/latest/pages/Developer%20guide/floating-point-comparisons.html

There are a few places in the code where we deliberately don't use COMPARE(), but they are special cases.  In general, using COMPARE() is much safer (or will be when we turn it on...).


**In COWD::ResolveAccretionRegime():**

- Same comment as above re local variable names - out convention is to (generally) start local variable names with lowercase letters.
- Same comment as above re COMPARE() macro


**In COWD::EvolveToNextPhase():**

While this is syntactically correct:

    m_Mass = m_Radius = m_Luminosity = m_Age = 0.0;

I think it is less readable than:

    m_Mass = 0.0;
    m_Radius = 0.0;
    m_Luminosity = 0.0;
    m_Age = 0.0;

(I actually prefer to line the "=" up, but I can live without that :-))

Again, the goal here is readability and maintainability.  The parser doesn't care whether we have the variables all initialised on a single line or on four lines - it just parses the code, tokenises it, and passes it on to the compiler as long as it is syntactically correct.  All the white space we put in and lining up of the statements between braces is just for the human reader - and making the code line up, putting plenty of white space in, declaring variables on separate lines etc., make it easier for humans to read the code.  As I said, it doesn't matter how "nice" it looks to the compiler - it'll parse whatever is syntactically correct - so you could just run all statements together in one giant line and it would parse ok (probably).  Whatever you can do to make the code "prettier" and easier to read for humans you should, and I think that includes declaring and/or initialising variable on separate lines.  It take very little time to do that once when you write it, but it save a lot of time for the hundreds or thousands of times a human will read it and find it easier to parse.

**In COWD.h:**

- STELLAR_TYPE EvolveToNextPhase(); // Modified to include evolution to ONe WD
Remove the comment - it will be obsolete and won't really apply as soon as we commit these changes.

- bool ShouldEvolveOnPhase(); // Evolve on phase unless mass > Chandrasekhar mass. Modified to include evolution to ONe WD
Ditto - remove the sentence starting with "Modified"


**In HeWD::DetermineAccretionRegime();**
    
- Accretion regime constants (see discussion above)
- Same comment as above re local variable names - our convention is to (generally) start local variable names with lowercase letters.
- Same comment as above re COMPARE() macro
- Same comment as above re constants that probably should be in constants.h


**In COWD::ResolveAccretionRegime():**

- Same comment as above re local variable names - our convention is to (generally) start local variable names with lowercase letters.
- Same comment as above re COMPARE() macro
- Same comment as above re constants that probably should be in constants.h


**COWD::ShouldEvolveOnPhase()** lacks documentation (i.e call signature, return value etc.)

**COWD::EvolveToNextPhas [...]

2022-06-29 02:26 UTC, solfreludio commented
> BaseBinaryStar.cpp:
> 
>     * why do you need "m_Accretor->SetMassTransferDiff(mdEnvAccreted);" on both lines 1895 and 1912?
You are right, this is not needed twice. I will update it accordingly.
> 
>     * @jeffriley will probably comment in more detail on the code, but AccretionRegime should be a defined type with values like ACCRETION_REGIME::NOVA or whatever, not arbitrary numbers like 10 that do not make sense when reading the code (note that 10 is not even defined in the comments, which only run 0--6);
I agree, this was just my way of doing it without much knowledge about how to define new things. What would be a good example to look at? Stellar types?
> 
>     * should a HeHG or HeGB star be treated as a giant?
Are you talking about line 1884? If so, it would not matter. This is linked to the ACCRETION_REGIME suggestion you made, since it is not clear from the code what accretion regime 10 stands for... also, as you probably noticed, I just copied and pasted the comments from COWD.cpp into HeWD.cpp, where accretion regime 10 is defined. This case is hydrogen rich accretion, so even if we include HeHG or HeGB they would not be considered for that particular channel. 
> 
>     * code starting line 1926 seems to almost repeat code starting line 1895; that's generally a bad idea (someone is likely to update code in one lace but not another in future changes, etc.), so it would be better to factor out common pieces of code into a separate function if necessary.
Yes, I will try to come up with something. The key difference is the second parameter for `DetermineAccretionRegime`, but this can be passed to the function that would wrap all the common pieces of codes.

2022-06-29 02:31 UTC, solfreludio commented
> BaseStar.h:
> 
>     * a lot of the internal variables introduced here are only relevant for WDs -- so why do they need to live in BaseStar.h, rather than WD.h or appropriate WD class?
This comes from me approach of "learning as I go" while coding. I found it worked and kept it, but yes, I was not sure about the placement. I will try moving things around and ask for help if necessary.
> 
>     * ```
>       double                  m_l0;                                       // Required for accretion limit onto HeWD
>       double                  m_lambda;                                   // Required for accretion limit onto HeWD
>       double m_X; // Required for accretion limit onto HeWD
>      *```
>       The comments should say what the variable stands for; I'd also recommend more descriptive names (e.g., lambda has other meanings in the code where it refers to envelope binding energy).
Sure, I can even put a reference to the paper where everything comes from. I was trying to avoid long lines.

2022-06-29 02:37 UTC, solfreludio commented
> COWD.cpp and elsewhere:
> 
> double LogMdot = log10(p_AccretedMass / p_Dt) - 6; // Logarithm of the accreted mass (M_sun/yr)
> 
> The choice of the time step Dt may not match the actual duration of the mass transfer phase in COMPAS. Therefore, it is unsafe to use Dt for determining the mass transfer rate. We do track the mass transfer rate _and_ the amount of mass transferred in BaseBinaryStar.cpp. These should be used directly, instead of relying on Dt.

I think we discussed this some time ago in Slack. I can't remember right now why I ended up choosing this method (I'm aware that there are some useful variables already implemented), so I will analyze it once again and give you a proper answer.

2022-06-29 05:49 UTC, solfreludio commented
> COWD.cpp:
> 
>     * I suggest including Log in all logged variable names for consistency;
> 
Noted
>     * m_Mass > 1.3
>       This should probably be defined somewhere; where does this choice come from?
> 
I must have removed the reference while cleaning the code. The idea comes from [Wang+ 2017](https://ui.adsabs.harvard.edu/abs/2017MNRAS.472.1593W/abstract), although their definition is a bit vague (one example shows 1.327 solar masses and later they say "when the CO WD grows in mass close to the Chandrasekhar limit"). So I discussed this with Ashley and eventually asked the main author directly. That is where the value comes from.
>     * If a COWD exceeds the Chandrasekhar mass through slow MT (no off-center ignition), it currently leaves behind a massless remnant -- is that correct?
Yes, this should be a "SN Ia"-like event. I think I should have also mentioned it at the beginning - it is one of my incomplete SN-event implementations.

2022-06-29 05:57 UTC, solfreludio commented
> Following up on COWD: Is the mass actually updated by the time the accretion regime is resolved?

This is a good point. I think that, at the moment, the accretion regime is being resolved at the following time step, so some episodes might be 'skipped' if the MT rate changes. Would it be better to try and move the call to this function to somewhere like `ResolveMassChanges` or `EvaluateBinary`?

2022-06-29 06:20 UTC, solfreludio commented
> WhiteDwarfs.cpp:
> 
> ```
> if (p_IsHeRich) {
>     thisMassRate = DonorMassRate * CalculateetaHe(p_LogDonorMassRate);
> } else {
>     thisMassRate = DonorMassRate * CalculateetaHe(p_LogDonorMassRate) * CalculateetaH(p_LogDonorMassRate);
> }
> 
> ```
> - Why is etaHe still used as a term in the MT accretion efficiency for H-rich donors?
From Claeys+ 2014, appendix B: "because first hydrogen is burned into helium, and subsequently helium is burnt into carbon and oxygen". I think this might also be related to something that has been bothering me, the changes through time of the hydrogen/helium shells in case a portion of the material is burnt (currently nothing is done about that).
> 
> WhiteDwarfs.h:
> 
>     * Where do the expressions for l0, X, and lambda come from?
The actual values come from [Ritter 1999](https://ui.adsabs.harvard.edu/abs/1999MNRAS.309..360R/abstract). The idea to use this specific paper comes from what is done in [Belczynski+ 2008](https://iopscience.iop.org/article/10.1086/521026/pdf), eq 60.

2022-06-29 06:32 UTC, solfreludio commented
> constants.h:
> 
> constexpr double M_HE_BUR = 0.35;
> 
>     * Is this consistent with the Hurley+ SSE choices?  Should we just use those values, since we use them elsewhere in the code?

Where are those values located? I tried searching in `constants.h` but could not find them, so I implemented my own constant. Reading in Hurley+ 2000, they mention that tier models for HeMS start at 0.32 M_Sun

2022-06-29 06:43 UTC, solfreludio commented
> General questions:
> 
>     * Do we want to fix the prescriptions / choices for accretion onto WDs, or create options for the user to explore different assumptions?
> 

A small comment here: this would also require settling for "pairs" of accretion regime limits and retention(accretion) efficiencies. For example, at the moment I'm using Piersanti+ 2014 for both the helium accretion regimes and the retention efficiencies. Similar situations occur with the studies by Wang and collaborators. But for hydrogen, not all prescriptions have these values published in "pairs".
Also, in this case we should settle for a "standard method" to deal with the extrapolation towards the low-mass range when this is not included. 

>     * Do we want to produce additional outputs letting the users know, e.g., when novae happen and how bright they are?
I think this might need additional work related to the size of the time step and the recurrence time of the events.
> 
> 
> You will need to update the changelog.h file and also the documentation (if extra input options or outputs are created).

2022-07-06 02:58 UTC, solfreludio commented
@ilyamandel @jeffriley I think I have addressed most of your suggestions. I have added `BaseBinaryStar::CalculateAccretionRegime` as a wrapper to avoid repeating the same blocks of code, although I'm not sure about the name I picked for the function.

Some other things to consider:
* How to properly compute the mass transfer rate. I'm basically using MassTransferredByDonor/TimeStep, but as Ilya pointed out (and as we discussed some time ago in Slack), this does not seem to be reliable. Using CalculateMassAcceptanceRate() is an option which I will test, but it seems this is just an upper limit for the mass transfer rate.
* I am not sure about which constants Jeff was talking about (in COWD.cpp, for example). 
* Where can I find the minimum mass for helium burning? Ilya mentioned they should be in the code, but I cannot seem to find them.
* I'm concerned about [this comment](https://github.com/TeamCOMPAS/COMPAS/pull/822#issuecomment-1169565047).
* Am I correctly triggering SN-like events? I do not think that this is the case, and I hope that these would pop up in the relevant logs (output).

Thanks for all your helpful insight!

2022-08-01 00:34 UTC, ilyamandel commented
Hi @solfreludio ,

Very sorry that it's taken so long to respond. 

Thank you for the nice changes, such as defining ACCRETION_REGIME. 

I invited you to join our next hack hour -- might be a faster way to respond to some of your points.  
Very briefly, until then:

`How to properly compute the mass transfer rate. I'm basically using MassTransferredByDonor/TimeStep, but as Ilya pointed out (and as we discussed some time ago in Slack), this does not seem to be reliable. Using CalculateMassAcceptanceRate() is an option which I will test, but it seems this is just an upper limit for the mass transfer rate.`

I still think that's dangerous, but we can talk more tomorrow.

`Where can I find the minimum mass for helium burning? Ilya mentioned they should be in the code, but I cannot seem to find them.`

Look for things like massCutoffs(MHeF) .

2022-08-10 06:54 UTC, jeffriley requested changes
Here's my review - it's fairly long, but much of it is just suggestions for keeping new code consistent with the conventions and style of the existing code. 


===================================================================


The function IncrementShell() should be renamed.  It is called from BaseBinaryStar::CalculateAccretionRegime():

m_Accretor->IncrementShell(p_MassAccreted * fractionAccretedMass, p_DonorIsHeRich); // Update variable that tracks shell size (H or He shell).

which is the binary star telling a constituent star to change one of the constituent star's attributes.  That's anti-pattern.  The correct way to do this is to have the binary star inform the constituent star of a change in its (the constituent star's) environment and allow the constituent star to react to that change.  It may well react by incrementing the size of its shell, but that should be left to the constituent star to decide, not the binary star.  We already have a function named "ResolveAccretion"I suggest renaming the function to something like "ResolveAccretion"

(I know there are probably places in the code where we come close to be anti-pattern, if not actually being anti-pattern, but we are trying to resolve those - so we don't want to add more).


===================================================================

In HeWD::ResolveAccretionRegime():

'pf' -> 'of' in comment
Description for p_Regime - it is not an integer (you changed it to ACCRETION_REGIME)
Add units to description of p_AccretedMass
Add units to the desription of p_Dt

/* Resolve what happens when the star goes through accretion regimes that might enable a change pf phase.
 * Flags are activated and the actual change happens elsewhere.
 *
 * void ResolveAccretionRegime(const int p_Regime, const double p_AccretedMass, const double p_Dt)
 *
 * @param   [IN]    p_Regime             Integer related to the current accretion regime
 * @param   [IN]    p_AccretedMass       Total mass accreted
 * @param   [IN]    p_Dt                 Size of the timestep, assumed to be the duration of this particular mass transfer episode
 */   
 
 
 Should the constants in this functon be defined in constants.h?  They are:

    double massSubCh = -4e8 * massTransfer + 1.34; // Minimum mass for Sub-Ch Mass detonation.
    double shellCrit = -7.8e-4 * massTransfer + 1.34; // Minimum shell mass of He for detonation. Should not be burnt, but not implemented this yet. Ruiter+ 2014.

    utils::Compare(massTransfer, 1.64e-6)

They only need to be in constants.h if they are used in multiple places in the code (so we only have to change them in one place if they ever need to be changed), or if they are used once but are well-known values.  What's really important is that we know where they come from and why they were used (rather than someone having to guess in 2 years' time...)


Change the 1e6 here to MYR_TO_YEAR (define in conastants.h) - if that's actually what you're doing (I assume it is):

    double massTransfer = p_AccretedMass / (p_Dt * 1e6);


I would probably rewrite this:	

    if ((utils::Compare(m_Mass, MASS_HELIUM_BURN) > -1) && (utils::Compare(m_HeShell, shellCrit) > -1) && (utils::Compare(massTransfer, 1.64e-6) < 0)) {
        m_Rejuvenate = true;
    } else if ((utils::Compare(m_Mass, MASS_HELIUM_BURN) > -1) && (utils::Compare(massTransfer, 1.64e-6) > -1)) {
        m_Rejuvenate = true;
    }
	
as this:

    if ((utils::Compare(m_Mass, MASS_HELIUM_BURN) >= 0) {
		if (utils::Compare(massTransfer, 1.64e-6) < 0) {
			if (utils::Compare(m_HeShell, shellCrit) >= 0)) {
				m_Rejuvenate = true;
			}
		}
		else {
			m_Rejuvenate = true;
		}
	}
		
I think it's easier to pick out what is happening, but that's a personal choice I'll leave to you.

Notice that as well as making the IF statements simpler, I also changed constructs like
 
    if (utils::Compare(m_Mass, MASS_HELIUM_BURN) > -1)

to

    if (utils::Compare(m_Mass, MASS_HELIUM_BURN) >= 0)

I did that because the utils::Compare() function was written to kind-of mirror the condition it replaces.  By that I mean

utils::Compare(m_Mass, MASS_HELIUM_BURN)

returns < 0 if m_Mass < MASS_HELIUM_BURN
        = 0 if m_Mass == MASS_HELIUM_BURN
		> 0 if m_Mass > MASS_HELIUM_BURN
		
Again, it's a personal thing, so up to you if you adopt that style, but it is more consistent with the current COMPAS conventions and style.


===================================================================

In COWD::ResolveAccretionRegime():

'pf' -> 'of' in comment
Description for p_Regime - it is not an integer (you changed it to ACCRETION_REGIME)
Add units to description of p_AccretedMass
Add units to the description of p_Dt

/* Resolve what happens when the star goes through accretion regimes that might enable a change pf phase.
 * Flags are activated and the actual change happens elsewhere.
 *
 * void ResolveAccretionRegime(const int p_Regime, const double p_AccretedMass, const double p_Dt)
 *
 * @param   [IN]    p_Regime             Integer related to the current accretion regime
 * @param   [IN]    p_AccretedMass       Total mass accreted
 * @param   [IN]    p_Dt                 Size of the timestep, assumed to be the duration of this particular mass transfer episode
 */ 
 
 
 Should the constants in this functon be defined in constants.h?  They are:

    if ((utils::Compare(logMdot, MDOT_OFF_C) > 0) && (utils::Compare(m_Mass, 1.3) > 0)) {


I think you should put the 6 into the parentheses here and change it to MYR_TO_YEAR (so you are using a symbolic name rather than just a "6") - it's not going to reduce efficiency much, and it helps people who look at the code later understand what the 6 means (and if we ever change the units of our timestep (god forbid...), then searching for "MYR_TO_YEAR" rather than "6" to find everywhere we convert MYR to YEAR is much easier...):

    double logMdot = log10(p_AccretedMass / p_Dt) - 6; // Logarithm of the accreted mass (M_sun/yr)

Why is the variable (effectively) "Mdot" here (log(Mdot) really), but "massTransfer" in HeWD::ResolveAccretionRegime()?


===================================================================

ONeWD::ResolveAccretionRegime() (in ONeWD.h):

Why is this defined here?  First, it has different parameters from all the other instances of the function, but even if that is resolved it's just the same as the BaseStar version of the function which is virtual and to which ONeWD would fall back to if the function was removed from ONeWD.h.
 
If you choose to leave the function definition in ONEwD.h, document why, add the extra parmeters, and remove the ';' inside the braces.


===================================================================

In BaseBinaryStar::CalculateMassTransfer():


If you add these to constants.h, just after the initializer list for COMPACT OBJECTS (look for "initializer_list<STELLAR_TYPE> COMPACT_OBJECTS" in constants.h):

    // (convenience) initializer list for GIANTS
    const std::initializer_list<STELLAR_TYPE> GIANTS = {
        STELLAR_TYPE::FIRST_GIANT_BRANCH,
	    STELLAR_TYPE::CORE_HELIUM_BURNING,
	    STELLAR_TYPE::EARLY_ASYMPTOTIC_GIANT_BRANCH,
	    STELLAR_TYPE::THERMALLY_PULSING_ASYMPTOTIC_GIANT_BRANCH
    };


    // (convenience) initializer list for WHITE DWARFS
    const std::initializer_list<STELLAR_TYPE> WHITE_DWARFS = {
        STELLAR_TYPE::HELIUM_WHITE_DWARF,
        STELLAR_TYPE::CARBON_OXYGEN_WHITE_DWARF,
        STELLAR_TYPE::OXYGEN_NEON_WHITE_DWARF
    };


    // (convenience) initializer list for He rich stellar types
    const std::initializer_list<STELLAR_TYPE> He_RICH_TYPES = {
        STELLAR_TYPE::NAKED_HELIUM_STAR_MS, 
        STELLAR_TYPE::NAKED_HELIUM_STAR_HERTZSPRUNG_GAP, 
        STELLAR_TYPE::NAKED_HELIUM_STAR_GIANT_BRANCH,
        STELLAR_TYPE::HELIUM_WHITE_DWARF
    };

you can then change these:

    bool accretorIsWD  = m_Accretor->IsOneOf({ STELLAR_TYPE::HELIUM_WHITE_DWARF, STELLAR_TYPE::CARBON_OXYGEN_WHITE_DWARF, STELLAR_TYPE::OXYGEN_NEON_WHITE_DWARF }) [...]

2022-09-05 00:49 UTC, solfreludio commented
I think that my latest update has addressed most of Jeff's comments. There are some parts where I did not add additional comments/documentation as I think that the papers being referenced are clear enough. Also, I implemented an additional user option to allow stripped He-cores to ignite when they are within 5% of the expected core mass at He ignition (MHeF). 

A major change is that I transitioned from using MassAccreted/TimeStep to the thermal mass loss rate of the donor... mainly because Ilya mentioned that while the timestep size can be modified by the user by using a multiplier, the mass value is fixed and therefore different multipliers would yield different results.

As a remaining "issue", I still have to check how to merge my "SN-like" events in the SN logs (sub Chandrasekhar "SN Ia" from He WDs and CO WD double detonation events).

2022-09-05 06:39 UTC, reinhold-willcox requested changes
Hi @solfreludio , 

Overall, I think this is a really useful addition to COMPAS and definitely appreciate you taking the time to put this together and respond to all the feedback. 

I skimmed through some of Ilya's and Jeff's comments, and generally agree. I'll add a few of my own based on the latest version here, which may be redundant with what Ilya and Jeff have previously written if they were not yet addressed. 

- You should update to the latest version of `dev`. There are some changes there with how we determine mass transfer stability which conflict with what you have here.
- Magic numbers should always be defined in constants.h, even if they are only used once and never changed. In a similar vein, why is the new option "AllowHeIgnitionAt95" hard-coded to 95? Does it make sense to implement this as a flexible value, or would it only ever be set to 95% if used?
- Some of the parameter/function names could be clearer, e.g including "log" or "threshold" to some of the "massTransferCrit" type variables, or spelling out "Hydrogen" and "Helium" in "CalculateEtaH". That's more personal preference, jeff or ilya might disagree. 
- It looks like "DetermineAccretionRegime" is identical in COWD.cpp and ONeWD.cpp - if that's intended, you should just write it once in COWD and let ONeWD inherit it.
- The functions you've added that pertain to only WDs should be in one of the WD classes. Specifically, CalculateAccretionRegime should not be in BaseStar. That's good code practice, but in this case it's also causing issues with the stability calculation. The m_FractionAccreted calculation is using the thermal timescale ratio that all other stellar types use to determine the mass transfer `beta`, but then you recalculate this accretion fraction specifically for WDs after we've already decided the MT should be stable. If the new value for m_FractionAccreted would have caused the MT to be come unstable, then we've done something wrong. However, I see that this function also applies mass gain onto the WD, and specifically needs to know if the material is Hrich or not, so the fix might be a bit non-trivial. I have some ideas for how to fix this, but it might be easier to explain in person. Are you able to join an upcoming code dev call?

2022-09-05 07:15 UTC, jeffriley commented
> Magic numbers should always be defined in constants.h, even if they are only used once and never changed. 

I would temper that a little and say that might be true ideally, but in practice it would become unwieldy in COMPAS' case.  It's a fine line, and a bit subjective, but in practice I would say if they are well-known, named, constants, and/or used often throughout the code, then yes, they belong in constants.h.  But we implement a lot of equations that have constants in them that are only ever used in the function in which they are implemented, e.g. take a look at these functions:

    HeMS::CalculateLuminosityAtZAMS_Static()
    HeMS::CalculateLuminosityAtPhaseEnd_Static()
    HeMS::CalculateLuminosityOnPhase_Static()
    HeMS::CalculateRadiusAtZAMS_Static()

They are just a few examples - we have, and will continue to have (just because of the way COMPAS works), many equations with constants implemented throughout the code, and pulling all the constants out and putting them in constants.h would be unwieldy.  In these instances I think it is sufficient to describe where the constants came from in comments in the code where the equations is implemented.

2022-09-05 07:31 UTC, jeffriley commented
> Some of the parameter/function names could be clearer, e.g including "log" or "threshold" to some of the "massTransferCrit"
> type variables, or spelling out "Hydrogen" and "Helium" in "CalculateEtaH". That's more personal preference, jeff or ilya might
> disagree.

I don't mind well-known/"accepted"/"standard" abbreviations, but also happy to spell out the word (provided it doesn't end up in a name so long it affects readability - remember compilers compile code, but humans have to read it).  A couple of guidelines though:

(a) don't abbreviate where it might be ambiguous.  e.g. abbreviating "Zeta" to "Z" is problematic - it could be confused with metallicity (Z) or redshift (z) depending upon case.

(b) consistency is as important as abbreviating or not - don't abbreviate in some places and not in others.  e.g. don't have one function called "CalculateZeta" and another called "CalculateZadiabatic" (as @reinhold-willcox will attest to) - use "CalculateZetaAdiabatic" (if other names aren't more appropriate (don't use "CalculateZ" to mean "CalculateZeta" - see (a)).

2022-09-06 03:21 UTC, solfreludio commented
>     * You should update to the latest version of `dev`. There are some changes there with how we determine mass transfer stability which conflict with what you have here.
Thanks for bringing this up, I think I have already merged things locally in my machine, though... I will try to find out what is happening!
>     * Magic numbers should always be defined in constants.h, even if they are only used once and never changed. In a similar vein, why is the new option "AllowHeIgnitionAt95" hard-coded to 95? Does it make sense to implement this as a flexible value, or would it only ever be set to 95% if used?
While the specific value depends on the physics considered on the models where this limit comes from, it seems that most values fall within this mass percentage. For details, see [section 3.1](https://ui.adsabs.harvard.edu/abs/2002MNRAS.336..449H/abstract) and table 1.
>     * Some of the parameter/function names could be clearer, e.g including "log" or "threshold" to some of the "massTransferCrit" type variables, or spelling out "Hydrogen" and "Helium" in "CalculateEtaH". That's more personal preference, jeff or ilya might disagree.
This is simple to fix, it all comes down to what everyone prefers. 
>     * It looks like "DetermineAccretionRegime" is identical in COWD.cpp and ONeWD.cpp - if that's intended, you should just write it once in COWD and let ONeWD inherit it.
Indeed, I will try to implement this change.
>     * The functions you've added that pertain to only WDs should be in one of the WD classes. Specifically, CalculateAccretionRegime should not be in BaseStar. That's good code practice, but in this case it's also causing issues with the stability calculation. The m_FractionAccreted calculation is using the thermal timescale ratio that all other stellar types use to determine the mass transfer `beta`, but then you recalculate this accretion fraction specifically for WDs after we've already decided the MT should be stable. If the new value for m_FractionAccreted would have caused the MT to be come unstable, then we've done something wrong. However, I see that this function also applies mass gain onto the WD, and specifically needs to know if the material is Hrich or not, so the fix might be a bit non-trivial. I have some ideas for how to fix this, but it might be easier to explain in person. Are you able to join an upcoming code dev call?
I can join next week :) But I think the problem here stems from naming conventions. The CalculateAccretionRegime modification to the accretion fraction is due to the "retention efficiency" that can be affected by flashes in the surface of the WD, or by "optically thick winds" if the accretion rate is too high. Also, the "new" fraction accreted is always equal or lower than the one computed initially.

2022-09-07 06:20 UTC, reinhold-willcox commented
@solfreludio Glad you liked my changes! There are some comments still in the code for things that remain to be addressed (all tagged with `// RTW: ...`). Some are things that you are better suited to, related to the actual implementation. Others I can do, such as cleaning up function headers for functions I modified. Are you ok if I push directly to your branch, `solfreludio:dev`?

2022-09-08 02:06 UTC, solfreludio commented
@reinhold-willcox sure, it is okay to push to my branch (although I'm not too experienced with permissions in github! if there is anything I have to do yo authorize you, please tell me). I did notice your comments, I will try to go over them between today/tomorrow.

2022-09-13 05:17 UTC, reinhold-willcox commented
Hey Nicolas, I have some questions based on our back and forth in the code. I think it'll be easier/quicker to ask here. 

1. In BaseBinaryStar, we have this instability condition for WDs if the acccretion regime is HeWD H accumulation. I had thought from your original PR that the MT always results in a CEE for this regime, and that it is additionally a merger if the donor is not a giant. Your comment: `// NRS: It is, but the CEE should only happen is the donor is a Giant, I'm not sure that's always the case here.` suggests otherwise. Can you clarify the intended functionality? Note that we consider all mergers to have gone through a CEE.

2. I've made `CalculateMassAcceptanceRate` and `DetermineAcccretionRegime` into separate functions in both HeWD.cpp and COWD.cpp (with ONeWD inheriting from COWD), which I think matches the intended functionality. The member variable `m_AccretionRegime` is set here, when the code calls for the accretion efficiency, and is later used when the mass is added back onto the accretor to determine whether it is He rich or not (in `WhiteDwarfs::ResolveShellChange`). I've left the eta functions in WhiteDwarfs.cpp, though arguably they should be in COWD if the HeWD never uses them. Can you verify that the way I've laid it out matches what you intended?

3. You reset some parameters, e.g `m_HShell`, `m_HeShell`, when each new WD type is initialized. Is there any risk that a WD switches type and needs to retain the previous quantity?

4. I am not so familiar with AICs vs Type Ias. Which types of WD can undergo which end states? And which types can switch to other types?
 
5. I'm still a bit perplexed by the cases where the accretion fraction is set to 1 (specifically, in `HeWD::CalculateMassAcceptanceRate`). I think what is missing is that the accretion should always be Eddington limited, as indicated in the last line of Claeys+ (2014) Appendix B. It should be straightforward to add a function to calculate the Eddington limit of a given WD, and ensure that the final MT rate (and corresponding efficiency) is capped at that value. However, I'm not sure if inclusion of the Eddington limit will impact the definition of the accumulation efficiency `eta`. Specifically, `eta` is usually defined as an efficiency on the accreted rate `Mdot_acu = eta * Mdot_acc`. If we think that all the donated material has the potential to be processed, we could set `Mdot_acc = Mdot_don`, calculate `eta` based on this (fairly high) rate, then truncate `Mdot_acu` to `Mdot_edd` if needed. Alternatively, if we think the Eddington limit prevents a lot of the donated material from reaching the WD surface in the first place, then we should set `Mdot_acc = min(Mdot_don, Mdot_edd)` before calculating the efficiency `eta`. I'm not really sure which is the right answer here, but I'll defer to you and Ashley as the experts. Let me know if that doesn't make sense.

2022-11-14 05:00 UTC, ilyamandel requested changes
I sincerely apologise for yet another delay, @solfreludio !

I tried to review the code from scratch.  A few things came up:

1. In COWD::CalculateMassAcceptanceRate(), I don't understand the second part of this comment:
m_AccretionRegime = DetermineAccretionRegime(p_IsHeRich, p_DonorMassRate); // Check if accretion leads to stage switch for WDs and returns retention efficiency as well.

2. In COWD::DetermineAccretionRegime(), it looks like some action is missing on double detonation?

3. In the same function, the value of 1.33 should probably be a constant defined elsewhere.

4. COWD::EvolveToNextPhase() -- there are question marks on the conditions here in the comments; resolve and remove question marks.

5. //void ResolveAccretionRegime(const ACCRETION_REGIME p_Regime, const double p_DonorThermalMassLossRate); -- commented out in COWD.h AND HeWD.h?  [remove commented out code if genuinely unnecessary; do we need this function at all?]

6. This one is for @reinhold-willcox ? 
Query on luminosity calculation in FGB::ResolveEnvelopeLoss()

7. HG descends from GiantBranch -- so should not need 
#include "GiantBranch.h"
in HG.cpp?

8. There's discussion between @solfreludio and @reinhold-willcox in the comments of HeWD.cpp .  For public code, please summarise the conclusion only.  (E.g., it's fair to say "The accretion regimes and of HeWDs are uncertain; we use the following models...")

9. ONeWD.cpp: the behaviour of when SNe happen does not appear to match our previously adopted thresholds (see COMPAS methods paper).

10. ONeWD.h: there are again SN queries from @reinhold-willcox -- let's clean up the comments.

11. Options.cpp -- again, queries from @reinhold-willcox in comments

12. WhiteDwarfs::CalculateetaH() and WhiteDwarfs::CalculateetaHe() -- some of the if / else logic could fail all conditions; is the returned eta intended to return 0.0 in this case? [aside: after if(A >=B), it's not really necessary to check else if (A<B && C>D) - enough to do else if (C>D)]

13. In WhiteDwarfs::ResolveAIC(), resolve @reinhold-willcox 's comments query; should probably include a check that the current mass is greater than MECS_REM (we should not be gaining mass on AIC).

14. In WhiteDwarfs::ResolveSNIa(), this comment is inaccurate:
//A Type 1a SN results in a massless remnant, which we are  here assuming to have a low mass equal to the ECSN remnant NS mass...

15. // RTW: Do we want to include He white dwarfs? If they are donors, is the material really He-rich in the same sense as the non-degen stars?
// (convenience) initializer list for He rich stellar types
const std::initializer_list<STELLAR_TYPE> He_RICH_TYPES = {

I think the answer is "yes" to both questions :)

16. Please add a new line to changelog.h and increment the version number.

2022-11-16 05:31 UTC, solfreludio commented
Note: I think some of the points raised in Reinhold's last post were discussed in some emails with Ashley... maybe we should copy the relevant points here
> I sincerely apologise for yet another delay, @solfreludio !
> 
No worries at all, thanks for your comments !

> I tried to review the code from scratch. A few things came up:
> 
>     1. In COWD::CalculateMassAcceptanceRate(), I don't understand the second part of this comment:
>        m_AccretionRegime = DetermineAccretionRegime(p_IsHeRich, p_DonorMassRate); // Check if accretion leads to stage switch for WDs and returns retention efficiency as well.

This is something we should have removed after Reinhold modified parts of the code while improving my first implementation. To make things clear, `DetermineAccretionRegime` used to be a tuple containing both the accretion regime and (what I like to call) retention efficiency. Now it just returns the accretion regime. Either way, I think it is better to just remove that comment, since it was a brief reference to what that function was doing. 
> 
>     2. In COWD::DetermineAccretionRegime(), it looks like some action is missing on double detonation?
> 
Yes, this is something I'm really not sure about "how to do", since I think it should be added to the SN log files. I can either try doing it myself (some pointers to where I should look at for references would be useful), or maybe @reinhold-willcox can look at it since (I think) he knows about these log files...?
>     3. In the same function, the value of 1.33 should probably be a constant defined elsewhere.
> 
Done, moved to `constants.h`.
>     4. COWD::EvolveToNextPhase() -- there are question marks on the conditions here in the comments; resolve and remove question marks.
> 
The double detonation section is linked to the missing elements in `COWD::DetermineAccretionRegime()`. According to what I have read, they should be (at least) candidates for SN Ia progenitors, but I can ask Ashley what she thinks about it.
I believe that the `IsMassAboveChandrasekhar()` case is correct, though I will wait for Reinhold's comments on that one.
>     5. //void ResolveAccretionRegime(const ACCRETION_REGIME p_Regime, const double p_DonorThermalMassLossRate); -- commented out in COWD.h AND HeWD.h?  [remove commented out code if genuinely unnecessary; do we need this function at all?]
> 
It seems this is also part of the leftovers from older versions of my work. I'm ok with removing them.

>     7. HG descends from GiantBranch -- so should not need
>        #include "GiantBranch.h"
>        in HG.cpp?
> 
Whoops, probably I added it when implementing the option to ignite the core below the expected core mass at helium flash.

>     12. WhiteDwarfs::CalculateetaH() and WhiteDwarfs::CalculateetaHe() -- some of the if / else logic could fail all conditions; is the returned eta intended to return 0.0 in this case? [aside: after if(A >=B), it's not really necessary to check else if (A<B && C>D) - enough to do else if (C>D)]
> 
Is this just being cautious or you think there is a value that is not included in the if/else logic? I will work on fixing the different checks, though.

2022-11-16 07:28 UTC, reinhold-willcox commented
I've made some changes that address a few of the points raised previously. I've throttled the donor mass loss rate by the Eddington limit where appropriate (though I think the limit could also be improved, see my post in the coding slack channel). 
I've also cleaned up some of the massRate and logMassRate confusion, so hopefully that's clearer now. I also renamed the constants relating to the accretion regime boundaries, and tried to add some text describing these changes. 

There are still remaining issues to address, both here and in comments in the source code, but please also double check that what I've done is correct. Notably, I swapped the mid and low thresholds for eta_He, which hopefully was a correction, but it would be great if someone could double check.

2022-11-16 20:56 UTC, ilyamandel commented
>> Yes, this is something I'm really not sure about "how to do", since I
think it should be added to the SN log files. I can either try doing it
myself (some pointers to where I should look at for references would be
useful), or maybe @reinhold-willcox <https://github.com/reinhold-willcox> can
look at it since (I think) he knows about these log files...?

I imagine that the simplest way to make sure that things get written to log
files would be to make sure that the supernova functions get called when we
go down this path...

On Wed, Nov 16, 2022 at 6:28 PM Reinhold Willcox ***@***.***>
wrote:

> I've made some changes that address a few of the points raised previously.
> I've throttled the donor mass loss rate by the Eddington limit where
> appropriate (though I think the limit could also be improved, see my post
> in the coding slack channel).
> I've also cleaned up some of the massRate and logMassRate confusion, so
> hopefully that's clearer now. I also renamed the constants relating to the
> accretion regime boundaries, and tried to add some text describing these
> changes.
>
> There are still remaining issues to address, both here and in comments in
> the source code, but please also double check that what I've done is
> correct. Notably, I swapped the mid and low thresholds for eta_He, which
> hopefully was a correction, but it would be great if someone could double
> check.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/TeamCOMPAS/COMPAS/pull/822#issuecomment-1316504628>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAD5BVKETFAJQHZ7W26DPQLWISEKRANCNFSM5ZWIYU3Q>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-11-16 22:51 UTC, reinhold-willcox commented
I am happy to add in the double detonation response. Do we want to treat it as (a) a Type Ia, (b) an AIC, or (c) a new category of its own?

2022-11-17 01:29 UTC, reinhold-willcox commented
@ilyamandel responding to some of your points above:

> 1. In COWD::CalculateMassAcceptanceRate(), I don't understand the second part of this comment:
m_AccretionRegime = DetermineAccretionRegime(p_IsHeRich, p_DonorMassRate); // Check if accretion leads to stage switch for WDs and returns retention efficiency as well.

Comment is now removed

> 6. This one is for @reinhold-willcox ?
Query on luminosity calculation in FGB::ResolveEnvelopeLoss()

This is related to some larger confusion I have with the FGB::ResolveEnvelopeLoss and HG::ResolveEnvelopeLoss functions. Specifically, I think the p_NoCheck parameter is confusing and should be (at least) renamed, but this discussion should happen with @jeffriley as well. 

> 8. There's discussion between @solfreludio and @reinhold-willcox in the comments of HeWD.cpp . For public code, please summarise the conclusion only. (E.g., it's fair to say "The accretion regimes and of HeWDs are uncertain; we use the following models...")

This has now been removed.

> 9. ONeWD.cpp: the behaviour of when SNe happen does not appear to match our previously adopted thresholds (see COMPAS methods paper).

Which thresholds specifically are you referring to? We currently use 1.38 Msun as the upper mass limit for ONeWD, consistent with the paper (though above this we induce a Type Ia SN, where the paper says AIC). Admittedly, we use 1.44 Msun as the upper mass limit for COWDs which have not switched over to ONeWDs, which is maybe a bit funny. But there are aspects of the methods paper that I expect will be out of date with these changes, e.g " Only stars in a narrow mass range of ≈ 7–8 Msun form ONeWD" is not true when we allow for COWDs to experience off center ignition. 

> 10. ONeWD.h: there are again SN queries from @reinhold-willcox -- let's clean up the comments.

It's still unclear to me what should happen if a ONeWD experiences off center ignition. This can currently occur in COMPAS, though possibly not in reality.

> 11. Options.cpp -- again, queries from @reinhold-willcox in comments

I added `percent` to the option name for clarity. Nicolas convinced me that this parameter can reasonably left as a hard coded 95% for now, and perhaps later we can generalize it if necessary.

> 12. WhiteDwarfs::CalculateetaH() and WhiteDwarfs::CalculateetaHe() -- some of the if / else logic could fail all conditions; is the returned eta intended to return 0.0 in this case? [aside: after if(A >=B), it's not really necessary to check else if (A<B && C>D) - enough to do else if (C>D)]

I've addressed these, but would appreciate it if someone double checked my fixes. 

> 13. In WhiteDwarfs::ResolveAIC(), resolve @reinhold-willcox 's comments query; should probably include a check that the current mass is greater than MECS_REM (we should not be gaining mass on AIC).

Agreed on adding the mass check. The reason for my comment is that this seems like a funny place to set the NS radius and luminosity. I would think they should be set automatically when the stellar type switches to NS. It looks like Nicolas copied this part of the code from `GiantBranch::ResolveElectronCaptureSN()`, which I would argue is also the wrong place to set these NS parameters. I have commented out these lines and added them to `NS.h`. Can @jeffriley comment on if this is the correct fix, or if I am missing something?

> 14. In WhiteDwarfs::ResolveSNIa(), this comment is inaccurate:
//A Type 1a SN results in a massless remnant, which we are here assuming to have a low mass equal to the ECSN remnant NS mass...

Not sure how that slipped through, probably I was copying the header from elsewhere. It is now fixed. 

> 15. // RTW: Do we want to include He white dwarfs? If they are donors, is the material really He-rich in the same sense as the non-degen stars?
// (convenience) initializer list for He rich stellar types
const std::initializer_list<STELLAR_TYPE> He_RICH_TYPES = {
>
> I think the answer is "yes" to both questions :)

Done, comment removed.

2022-11-17 21:38 UTC, jeffriley commented
> This is related to some larger confusion I have with the FGB::ResolveEnvelopeLoss and HG::ResolveEnvelopeLoss functions.
> Specifically, I think the p_NoCheck parameter is confusing and should be (at least) renamed, but this discussion should
> happen with @jeffriley as well.

ResolveEnvelopeLoss() modifies the star's attributes after it loses its envelope - if it in fact lost its envelope.  Most (probably all?) stellar types have their own ResolveEnvelopeLoss() functions.  ResolveEnvelopeLoss() first checks whether the envelope has in fact been lost - the check is core mass >= mass - if that is true then the envelope is gone and the attributes of the star are updated - one of which is the radius (see later).  We don't want to update the attribute if the star hasn't actually lost its envelope, even if the updates would be benign (in terms of affecting the attributes of the start) - the calculations are not trivial, so we don't want to negatively affect performance by doing non-trivial calculations that are not necessary.

The p_NoCheck parameter of the function allows callers of the function to force the calculations to happen - that is, if p_NoCheck is passed as true, no check is performed, and the star's attributes are update without checking whether it still has an envelope.  p_NoCheck is (currently) only passed as true in two places in the code - in:

GiantBranch::CalculateRadialExtentConvectiveEnvelope()
HG::CalculateRadialExtentConvectiveEnvelope()

and in both those cases we clone the star and the call ResolveEnvelopeLoss(true) to force the calculations so we can pick up the newly calculated radius of the star.

So, that's why the parameter exists and what it is for.  Sure, feel free to rename it to "p_ForceUpdate" or something (and a version of the explanation above should probably be put in the comments describing the ResolveEnvelopeLoss() function (in every stellar type cpp file...) so everybody knows what it's for.

We could do it differently.  We could have separate functions - one that checks and one that doesn't.  They'd both call the underlying function, just one would not check before calling.  If you think that would be more clear, then I'm ok with that.

Or, we could figure out if we really need the check at all.  The reason it is there is because the legacy code did the check, and bypassed it (differently, but still bypassed it) in the two cases described above.  The two cases where we bypass the check, we're just trying to figure out the new radius of the star after losing its envelope - we don't want to update it yet, we just want to know what the value would be.  When I ported the code I wondered if bypassing the check was actually required.  If we call 
ResolveEnvelopeLoss() and *always* perform the check for envelope loss, then in the event of no envelope loss the radius of the star would be unchanged, and we would use that unchanged radius in the two cases above (that have p_NoCheck = true).  I planned to check if that actually made a difference, but I never got back to it.

However...  I just checked the code, and the only place I can find that we call CalculateRadialExtentConvectiveEnvelope() is from
BaseStar::CalculateEddyTurnoverTimescale(), which is only ever called from 
BinaryConstituentStar::CalculateCircularisationTimescale() and BinaryConstituentStar::CalculateSynchronisationTimescale(), and neither of those functions is ever called.  Is that right, or am I missing something?

Ok, so if those functions (BinaryConstituentStar::CalculateCircularisationTimescale() and BinaryConstituentStar::CalculateSynchronisationTimescale()) are never called, then while that remains true we don't actually need the p_NoCheck parameter.  The question is, why are those functions never called?  Were they always just superfluous and never called, or did we change something along the way that obviated the need for those functions?  I would hesitate to pull the p_NoCheck parameter out unless we also remove both BinaryConstituentStar::CalculateCircularisationTimescale() and BinaryConstituentStar::CalculateSynchronisationTimescale() - as long as they exist in t he code base, someone could use them, and then the p_NoCheck parameter is required (unless we do the tests to see if it was ever really required).

Does anybody know why we don't call BinaryConstituentStar::CalculateCircularisationTimescale() or BinaryConstituentStar::CalculateSynchronisationTimescale()?  Or am I just missing the calls?

2022-11-17 21:54 UTC, ilyamandel commented
>> Does anybody know why we don't call
BinaryConstituentStar::CalculateCircularisationTimescale() or
BinaryConstituentStar::CalculateSynchronisationTimescale()? Or am I just
missing the calls?

Because one of our to-do items is checking and enforcing our implementation
of tides -- which is where these two functions are needed. :-)

On Fri, Nov 18, 2022 at 8:38 AM jeffriley ***@***.***> wrote:

> This is related to some larger confusion I have with the
> FGB::ResolveEnvelopeLoss and HG::ResolveEnvelopeLoss functions.
> Specifically, I think the p_NoCheck parameter is confusing and should be
> (at least) renamed, but this discussion should
> happen with @jeffriley <https://github.com/jeffriley> as well.
>
> ResolveEnvelopeLoss() modifies the star's attributes after it loses its
> envelope - if it in fact lost its envelope. Most (probably all?) stellar
> types have their own ResolveEnvelopeLoss() functions. ResolveEnvelopeLoss()
> first checks whether the envelope has in fact been lost - the check is core
> mass >= mass - if that is true then the envelope is gone and the attributes
> of the star are updated - one of which is the radius (see later). We don't
> want to update the attribute if the star hasn't actually lost its envelope,
> even if the updates would be benign (in terms of affecting the attributes
> of the start) - the calculations are not trivial, so we don't want to
> negatively affect performance by doing non-trivial calculations that are
> not necessary.
>
> The p_NoCheck parameter of the function allows callers of the function to
> force the calculations to happen - that is, if p_NoCheck is passed as true,
> no check is performed, and the star's attributes are update without
> checking whether it still has an envelope. p_NoCheck is (currently) only
> passed as true in two places in the code - in:
>
> GiantBranch::CalculateRadialExtentConvectiveEnvelope()
> HG::CalculateRadialExtentConvectiveEnvelope()
>
> and in both those cases we clone the star and the call
> ResolveEnvelopeLoss(true) to force the calculations so we can pick up the
> newly calculated radius of the star.
>
> So, that's why the parameter exists and what it is for. Sure, feel free to
> rename it to "p_ForceUpdate" or something (and a version of the explanation
> above should probably be put in the comments describing the
> ResolveEnvelopeLoss() function (in every stellar type cpp file...) so
> everybody knows what it's for.
>
> We could do it differently. We could have separate functions - one that
> checks and one that doesn't. They'd both call the underlying function, just
> one would not check before calling. If you think that would be more clear,
> then I'm ok with that.
>
> Or, we could figure out if we really need the check at all. The reason it
> is there is because the legacy code did the check, and bypassed it
> (differently, but still bypassed it) in the two cases described above. The
> two cases where we bypass the check, we're just trying to figure out the
> new radius of the star after losing its envelope - we don't want to update
> it yet, we just want to know what the value would be. When I ported the
> code I wondered if bypassing the check was actually required. If we call
> ResolveEnvelopeLoss() and *always* perform the check for envelope loss,
> then in the event of no envelope loss the radius of the star would be
> unchanged, and we would use that unchanged radius in the two cases above
> (that have p_NoCheck = true). I planned to check if that actually made a
> difference, but I never got back to it.
>
> However... I just checked the code, and the only place I can find that we
> call CalculateRadialExtentConvectiveEnvelope() is from
> BaseStar::CalculateEddyTurnoverTimescale(), which is only ever called from
> BinaryConstituentStar::CalculateCircularisationTimescale() and
> BinaryConstituentStar::CalculateSynchronisationTimescale(), and neither of
> those functions is ever called. Is that right, or am I missing something?
>
> Ok, so if those functions
> (BinaryConstituentStar::CalculateCircularisationTimescale() and
> BinaryConstituentStar::CalculateSynchronisationTimescale()) are never
> called, then while that remains true we don't actually need the p_NoCheck
> parameter. The question is, why are those functions never called? Were they
> always just superfluous and never called, or did we change something along
> the way that obviated the need for those functions? I would hesitate to
> pull the p_NoCheck parameter out unless we also remove both
> BinaryConstituentStar::CalculateCircularisationTimescale() and
> BinaryConstituentStar::CalculateSynchronisationTimescale() - as long as
> they exist in t he code base, someone could use them, and then the
> p_NoCheck parameter is required (unless we do the tests to see if it was
> ever really required).
>
> Does anybody know why we don't call
> BinaryConstituentStar::CalculateCircularisationTimescale() or
> BinaryConstituentStar::CalculateSynchronisationTimescale()? Or am I just
> missing the calls?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/TeamCOMPAS/COMPAS/pull/822#issuecomment-1319238610>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAD5BVITA7TFZKVAVWRZRC3WI2QWDANCNFSM5ZWIYU3Q>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-11-18 00:24 UTC, solfreludio commented
> > 10. ONeWD.h: there are again SN queries from @reinhold-willcox -- let's clean up the comments.
> 
> It's still unclear to me what should happen if a ONeWD experiences off center ignition. This can currently occur in COMPAS, though possibly not in reality.
> 
As far as I know, this should not be possible (or at least it has not been explored).

---

> > 11. Options.cpp -- again, queries from @reinhold-willcox in comments
> 
> I added `percent` to the option name for clarity. Nicolas convinced me that this parameter can reasonably left as a hard coded 95% for now, and perhaps later we can generalize it if necessary.
> 
Yes, I'm currently exploring what's the real impact for a given percentage (or the use of a _prescription_) in the final yield of sdB candidates. But that's for the future, this current option looks fine 😄 

---

> > 12. WhiteDwarfs::CalculateetaH() and WhiteDwarfs::CalculateetaHe() -- some of the if / else logic could fail all conditions; is the returned eta intended to return 0.0 in this case? [aside: after if(A >=B), it's not really necessary to check else if (A<B && C>D) - enough to do else if (C>D)]
> 
> I've addressed these, but would appreciate it if someone double checked my fixes.
> 
I have checked and everything looks fine. Also, you left a question to my comment: `// Modified so we can have double detonations // RTW: what does this mean? Should this be 0.0?`. What I mean is that, as you probably noticed, this is 0 in Claeys+ 2014. However, using 0 leads to no growth of the helium shell right where Piersanti+ 2014 indicate that there is an "accumulation" regime that leads to double detonations. This is confusing to me as well, since Claeys+ 2014 assume 0 as the material is not burning (not steadily nor in flashes), but that does not mean you would not accrete and pile it up on the surface. According to Piersanti+ 2014:

> ... we found that, at constant low accretion rates (from ~ 5 × 10^-8 Msol yr^-1 for 1.02 Msol WDs to ~2 × 10^-8 Msol yr^-1 for 0.6 Msol WDs), the accretion timescale is much longer than the inward thermal diffusion timescale, so that conditions at the base of the He layer are defined by the interplay between neutrino cooling and energy release by contraction of accreted matter. Helium is deposited quietly at the surface of the CO dwarf and piled up for a long time...

---

2022-11-18 00:32 UTC, jeffriley commented
> ... GiantBranch::ResolveElectronCaptureSN(), which I would argue is also the wrong place to set these NS parameters.
> I have commented out these lines and added them to NS.h. Can @jeffriley comment on if this is the correct fix, or if I
> am missing something?

I'm not sure of the correct answer here - I think it may need some more looking into...

A few points:

(a) we don't call things like CalculateRadiusOnPhase() and CalculateLuminosityOnPhase() in the Initialise() function for any of the stellar types except HG and HeHG.  I would think that the transition of attributes such as radius and luminosity should be smooth and continuous from one stellar type to the next, so (e.g.) the radius at the start of t he phase should be the same as the radius at the end of the previous change (there are no timesteps between phases).  I think we do call these for HG and HeHG because at some stage there was a discontinuity for those stellar types, and we fixed the problem by calling those functions at the start of the phase (in Initialise()).  I think (but I may not be recalling that correctly).

Having said that though, maybe the transition to NS is not smooth and continuous wrt radius and luminosity.  But why do we not currently call those functions in Initialise() for NS?  If we should be calling them, why haven't we noticed a problem so far - because the values are calculated at the first timestep anyway and we just don't notice?  Possible I suppose.

Wrt the question as o why the values are being set in GiantBranch::ResolveElectronCaptureSN() - we set them in all the "Resolve...SN()" functions.  The difference between setting them there and not in Initialise(), is that by setting them in (e.g.) GiantBranch::ResolveElectronCaptureSN() the values of the class member variables (e.g. m_Radius) are changed immediatley, whereas if we don't set them in (e.g.) GiantBranch::ResolveElectronCaptureSN() but instead rely on them being set in Initialse(), the values will not change until the end of the timestep (when the stellar type switch is actually performed.).

This may be highlighting a defect - or not (I'm leaning towards maybe it is, but I think I need to look at the code a bit more and think about it...).  Before I describe the possible defect, I will point out some similar anomalous behaviour in GiantBranch::ResolveCoreCollapseSN():

    if (OPTIONS->RemnantMassPrescription() == REMNANT_MASS_PRESCRIPTION::MULLER2016) {
        stellarType = CalculateRemnantTypeByMuller2016(m_COCoreMass);
    }
    else if (OPTIONS->RemnantMassPrescription() == REMNANT_MASS_PRESCRIPTION::MULLERMANDEL) {
        if (utils::Compare(m_Mass, MULLERMANDEL_MAXNS ) > 0)
            stellarType = STELLAR_TYPE::BLACK_HOLE;
        else
            stellarType = STELLAR_TYPE::NEUTRON_STAR;
    }
    else if (OPTIONS->RemnantMassPrescription() == REMNANT_MASS_PRESCRIPTION::HURLEY2000) {
        stellarType = (utils::Compare(m_Mass, 1.8 ) > 0) ? STELLAR_TYPE::BLACK_HOLE : STELLAR_TYPE::NEUTRON_STAR; //Hurley+ 2000, Eq. (92)
    }
    else if (utils::Compare(m_Mass, OPTIONS->MaximumNeutronStarMass()) > 0) {
        std::tie(m_Luminosity, m_Radius, m_Temperature) = BH::CalculateCoreCollapseSNParams_Static(m_Mass);
        stellarType = STELLAR_TYPE::BLACK_HOLE;
    }
    else {
        std::tie(m_Luminosity, m_Radius, m_Temperature) = NS::CalculateCoreCollapseSNParams_Static(m_Mass);
        stellarType = STELLAR_TYPE::NEUTRON_STAR;
    }

For some of the "else" blocks we set the stellar type (we should switch to) to BH or NS, and set the new radius, luminosity, and temperature by calling BH::CalculateCoreCollapseSNParams_Static() or NS::CalculateCoreCollapseSNParams_Static() accordingly - but others don't update the radius, luminosity, and temperature?  Why is that?

Ok, the possible defect.  I would have followed the legacy code in updating the radius and luminosity in the "Resolve...SN()" functions.  The legacy code did most of the updating of the star's attributes inline rather than in callable functions (though there were some SN functions - but I don't remember what they did specifically).  It doesn't really matter, except to explain what the possible defect might be.

The legacy code didn't have classes for each of the stellar types - it had just the Star class and the Binary class from memory.  The stellar type of a star was governed by a variable, and that variable was checked in a big switch statement.  In that switch statement, if it was determined that a star should change stellar type, the stellar type variable was changed, and the star's attributed (radius etc.) were updated.  Each statement to change something - stellar type, radius, mass, etc., was executed immediately.  The consequence of that immediate execution was that calculations that were dependent upon the values of stellar type or other attributes of the star were performed using the newly updated values - which is fine if things are done (and can be done) in the right order.  However, the new code is advised what the new stellar type should be, and that switch is done at the end of the timestep (in most cases).  So in the "Resolve...SN" functions we set our (local) stellar type variable, and the switch to that stellar type will be done at the end of the timestep.  But the changes to class member variables (e.g. m_Radius, m_Luminosity, etc.) take immediate effect.  That means for the remainder of the timestep we are working with updated radius, luminosity, etc., but we haven't yet switched to the new stellar type (so any calls to functions that calculate and change things are for the existing stellar type, not the one we know we're about to switch to).  I think in most cases we don't actually do much in the remainder of the timestep that would cause us trouble, but I don't really know for sure (hence the comment that this might need some more looking into...).

2022-11-28 00:40 UTC, ilyamandel requested changes
A reminder that:

- The documentation needs to be updated to include the new option p_Options->m_HeIgnitionPercentRGB

- This option should be included in the default .yaml file

- changelog should be updated

I'd like to see this pulled soon, so that we can proceed with testing, etc.  Can I therefore suggest that we focus on the clear must-make changes and create issues for future improvements / enhancements for places where we are not yet certain about what these should be?

2022-11-28 04:38 UTC, reinhold-willcox commented
@ilyamandel happy to address those changes, but we're still waiting on @jeffriley to look at the p_NoCheck argument (since @solfreludio  has used it for other purposes here, so I want to make sure it's doing what we think it's doing), and on @solfreludio  to confirm what actions should be taken under double detonation.

2022-11-28 23:31 UTC, jeffriley commented
@reinhold-willcox @ilyamandel @solfreludio 

> waiting on @jeffriley to look at the p_NoCheck argument (since @solfreludio has used it for other purposes here, 
> so I want to make sure it's doing what we think it's doing)

The p_NoCheck parameter to *::ResolveEnvelopeLoss() does what I described it does above - I don't know if that matches what everybody else thinks it does.  But the real question is whether we need it...

As I described above, the p_NoCheck parameter to ResolveEnvelopeLoss() overrides the check at the top of the function that checks whether the star actually has lost its envelope - if p_NoCheck is TRUE, the check is not performed.  What that means is that if p_NoCheck is TRUE, the loss of the star's envelope is resolved (i.e. attributes of the star are recalculated) whether it has lost it's envelope or not...  As I mentioned above, this came from the legacy code, and, when I refactored the code, I was going to run some tests to see if the p_NoCheck parameter was actually required.  I did not get around to doing that - until today.

The check at the top of the *::ResolveEnvelopeLoss() functions is to determine if in fact the star has lost its envelope - no point resolving the loss of an envelope if the envelope was not actually lost...  That check is implemented differently for different stellar types.  Here are the current checks by stellar type:

    MS    : m_Mass <= 0
    HG    : m_CoreMass > m_Mass
    FGB   : m_CoreMass > m_Mass
    CHeB : m_CoreMass >= m_Mass
    EAGB : m_HeCoreMass >= m_Mass
    TPAGB: m_CoreMass >= m_Mass
    HeMS : m_Mass <= 0.0
    HeHG : m_COCoreMass >= m_Mass

Other stellar types inherit as usual.

I ran a test of 100,000 binaries, and found that the only time ResolveEnvelopeLoss() was called with p_NoCheck = TRUE and the envelope lost check at the top of the function was not satisfied (i.e. p_NoCHECK = TRUE actually overrode the envelope lost check) was for stellar types HG and FGB, and only when m_CoreMass = m_Mass.  Note that, from above, the check for stellar types HG and FGB was not consistent with other stellar types: the condition for HG and FGB was ">", whereas it is ">=" (or "<=") for all other stellar types.

I changed the condition in the check at the top of the function for stellar types HG and FGB from ">" to ">=", and ran a test of 1 million binaries.  At no time in that run was ResolveEnvelopeLoss() called with p_NoCheck = TRUE and the envelope lost check at the top of the function was not satisfied - i.e. every call to ResolveEnvelopeLoss() with p_NoCheck = TRUE would have resulted in the code being executed anyway because the envelope lost check was also satisfied.  It would seem then that the p_NoCheck parameter is superfluous and can safely be removed.  Note that in the current code (prior to this PR), the p_NoCheck parameter was only ever set TRUE when the function is called for a cloned star - when we want to know what would happen to the radius of the star without actually making the change.

My recommendation is to change the ResolveEnvelopeLoss() function for HG and FGB as described above, and remove the p_NoCheck parameter for all variants of the function (and callers) - with the caveat that I haven't checked yet how Nicolas is using it.

Does anyone disagree?

2022-11-29 00:55 UTC, reinhold-willcox commented
Thanks @jeffriley ! I'm happy with that, though I know Ilya had some concerns about removing it if it would just be reimplemented for tracking tides. 

I'll pass it off to @solfreludio to comment on what the path forward should be for his code, and when the `if (p_NoCheck)` clauses are intended to be true.

2022-11-29 00:58 UTC, jeffriley commented
> Thanks @jeffriley ! I'm happy with that, though I know Ilya had some concerns about removing it if it would just
> be reimplemented for tracking tides.

It won't affect the tides implementation.  ResolveEnvelopeLoss() will still be called, just without the p_NoCheck parameter.

2022-11-30 03:14 UTC, solfreludio commented
My use of `p_NoCheck` was motivated by looking for a simple way to trigger the helium core ignition below the expected core mass at the helium flash when the star loses its envelope relatively fast (CE-like). Removing `p_NoCheck` from the condition should be fine, although I think that it would be a good idea to replace it with a check on the envelope loss rate, if possible. Or, just check if the envelope was lost through a CE episode, which I think should be an equivalent condition.

As for updating the documentation, I guess that [this](https://github.com/TeamCOMPAS/COMPAS/tree/dev/online-docs) is what I should be looking at?

2022-11-30 07:28 UTC, jeffriley commented
> Removing p_NoCheck from the condition should be fine, although I think that it would be a good idea to replace it 
> with a check on the envelope loss rate, if possible. Or, just check if the envelope was lost through a CE episode, which 
> I think should be an equivalent condition.

I we just remove the p_NoCheck parameter to the *::ResolveEnvelopeLoss() functions, we would leave the checks as described above.  If you want to add/change those checks, then you need to determine what effect that would have on other code calling *::ResolveEnvelopeLoss().   Right now we know (well, we think we know) those checks are sufficient for the code as it is now, but if your code needs a different, or modified check, that has to co-exist with the other callers of the function.

2022-11-30 11:55 UTC, reinhold-willcox commented
@jeffriley I think Nicolas is referring to the new clause in his PR that uses p_NoCheck. 

@solfreludio, as Jeff pointed out above, the flag is in practice never TRUE, so the code you wrote to ignite He at lower masses will never be executed. I'm not sure I follow what you described as the intended trigger. Should this clause only ever run if the envelope was stripped in a CEE?

2022-11-30 18:55 UTC, jeffriley commented
Ok.  But

> ...  as Jeff pointed out above, the flag is in practice never TRUE ...

that's not true.  As the code is currently written, the p_NoCheck parameter is sometimes TRUE but, in my test, in all cases that it was TRUE the other half of the conditional (i.e. the mass check) was also TRUE, so the p_NoCheck parameter was superfluous.  That's different from it not being TRUE - in fact the overwhelming majority of calls to ResolveEnvelopeLoss() are with p_NoCheck = FALSE (so in most calls it is not TRUE).

2022-11-30 23:31 UTC, solfreludio commented
Yes, I was only talking about the clause on my PR that uses `p_NoCheck`.

@reinhold-willcox yes, the idea is to allow this clause only after the envelope is removed through a CE episode, and looking into the code I realize is not working like that. From the code, I noticed that `ResolveEnvelopeLossAndSwitch` was being called during `ResolveCommonEnvelopeEvent` if one of the stars in the binary lost its envelope. But it seems the same function is called during stable MT as well. Oh, and since `ResolveEnvelopeLossAndSwitch` calls `ResolveEnvelopeLoss` with `p_NoCheck == true` I figured I had to include that flag in my clause.

2022-11-30 23:45 UTC, jeffriley commented
> ... since ResolveEnvelopeLossAndSwitch calls ResolveEnvelopeLoss with p_NoCheck == true

Oh, so it does...  That's an interesting thing.  It does that, I assume, because we have previously determined that the star has lost its envelope - see the 'envelopeFlag1' and 'envelopeFlag2' flags.  But those flags are set based on the core mass of the star, whereas the *::ResolveEnvelopeLoss() functions us core mass, CO core mass, and He core mass variously.  That could be an issue...

2022-12-01 03:54 UTC, reinhold-willcox commented
For the time being, I have removed the parts of this PR that depend on the p_NoCheck flag, while we determine the scope of its influence and whether it can safely be removed (and also, what conditions Nicolas needs for the He Ignition clause). This includes the new option for He Ignition below the nominal RGB threshold. That way, we can finish off this PR on a short timescale. I will open a new PR for the He Ignition feature, which can be reviewed at a later point. 

Thus the remaining issues to be addressed for this PR include:

1. `COWD.cpp` line 77, what to do if your total and He shell masses are above the specified critical masses. @solfreludio 
2. `HeWD.cpp` line 130, whether we need to set additional properties of the reborn HeMS star (R, L, age, tau, etc.). @jeffriley 
3. Double check that the conditions, thresholds, and outcomes of the different accretion regimes are correctly implemented in the source code, and that the code works correctly when run in these different regimes. @solfreludio 
4. Update documentation. @solfreludio and @reinhold-willcox 

Did I miss anything?

2022-12-01 04:11 UTC, jeffriley commented
> ... the p_NoCheck flag, while we determine the scope of its influence and whether it can safely be removed

Do you mean generally, or specifically for Nicolas?  If you mean generally, I can state that I 100% understand the scope of influence of the p_NoCheck parameter, and that it can safely be removed.  I can push a change to do that if you want.

2022-12-01 04:39 UTC, reinhold-willcox commented
> But those flags are set based on the core mass of the star, whereas the *::ResolveEnvelopeLoss() functions us core mass, CO core mass, and He core mass variously. That could be an issue...

You're sure that this above issue won't be a concern?

2022-12-01 05:01 UTC, jeffriley commented
> You're sure that this above issue won't be a concern?

Not at all.  I think it is a concern, but it is independent of the p_NoCheck parameter.  

First, I know from my test of 1 million binaries that setting p_NoCheck to TRUE has no effect - whenever it was true, so was the mass check in ResolveEnvelopeLoss().

The concern is that BaseBinaryStar::ResolveCommonEnvelopeEvent() detemines the values of the 'envelopeFlag1' and 'envelopeFlag2' flags based on the core mass, then calls ResolveEnvelopeLossAndSwitch(), which calls ResolveEnvelopeLoss(TRUE).  So BaseBinaryStar::ResolveCommonEnvelopeEvent() is saying "the star has lost its envelope - update its attributes".  But ResolveEnvelopeLoss() will only update the star if it thinks the envelope has been lost, and it uses a different criterion (or criteria if we look at *::ResolveEnvelopeLoss()).  It seems not to matter - that we know of.  In the 1M binary test I did, it didn't matter.  But maybe one day it will...  We could leave p_NoCheck in, but that would only mask the problem.  The problem is that we use different criteria to determine if the envelope has been lost.  I think if we want to do it properly we would have a function in each stellar class that determines if the envelope has been lost (using the criteria in ResolveEnvelopeLoss()) and call that from BaseBinaryStar::ResolveCommonEnvelopeEvent().  I think this came about because some time in the recent past @ilya changed the *::ResolveEnvelopeLoss() functions to use the "correct" core mass (but I might be misremembering that), so the checks there got out of sync with the checks in BaseBinaryStar::ResolveCommonEnvelopeEvent().

2022-12-01 06:20 UTC, jeffriley commented
> HeWD.cpp line 130, whether we need to set additional properties of the reborn HeMS star (R, L, age, tau, etc.).

FGB.cpp?

2022-12-01 22:07 UTC, reinhold-willcox commented
> > HeWD.cpp line 130, whether we need to set additional properties of the reborn HeMS star (R, L, age, tau, etc.).

> FGB.cpp?

No HeWD.cpp, in this new PR. You can resurrect a HeMS from a HeWD with accretion.

2022-12-01 22:20 UTC, jeffriley commented
Oh, ok - new code.  There wasn't any code in COWD.cpp or HeWD.cpp before this PR.  I don't know the answer off the top of my head.  COWD and HeWD inherit from WhiteDwarfs - what happens there?  Not all attributes need to be recalculated in the *::Initialise() functions - often we can just use the value of an attribute from the previous phase (which is inherited) - the phase transitions are mostly smooth and continuous.  What does Hurley+2000 indicate (if anything)?

2022-12-05 00:07 UTC, solfreludio commented
>     1. `COWD.cpp` line 77, what to do if your total and He shell masses are above the specified critical masses. @solfreludio 

I think I overlooked this before, but the `m_DoubleDetonation = true;` line should be inside the clause, as the double detonation should be triggered only when you are in the right regime, with the right mass and shell mas values. The shell value might be implemented as user-provided in the future, if needed. For now, this is what I based the current value on (Ruiter+ 2014):

> We also explore the case where a double
detonation is presumed to occur with an He shell mass of 0.05 M.
This is a more reasonable assumption given recent studies of He
accretion with 1D hydrodynamical simulations in the context of
double detonations (Woosley & Kasen 2011, see also Moore et al.
2013). However, this critical shell mass likely depends on the WD
mass (see e.g. Bildsten et al. 2007)

2022-12-16 21:43 UTC, jeffriley commented
See issues #873 and #874

2023-01-17 07:07 UTC, reinhold-willcox commented
@solfreludio Sorry for the silence, I've just made a couple changes listed above. 

The remaining TODO items for this are
1. Documentation
2. ONeWD.cpp: Can you confirm that there should be a SN Ia if the mass is above the ECSN threshold?
3. Whitedwarfs.cpp: Can you confirm the value of `eta=1.0` in the final if/else clause of `CalculateEtaHe()`?

Once those 3 are done, we should be able to wrap up this PR.

2023-02-11 23:38 UTC, ilyamandel commented
@solfreludio , @reinhold-willcox -- thanks a lot for all of your work on this PR!  Is it ready to go? :)

2023-02-12 08:12 UTC, reinhold-willcox commented
@ilyamandel Waiting only on some documentation changes which Nicolas said he would take care of. It's otherwise ready for you or @jeffriley to review!

2023-02-13 03:32 UTC, solfreludio commented
I believe I have addressed the necessary documentation updates. Let me know if you think that more updates are needed

2023-02-15 22:58 UTC, jeffriley requested changes
Reviewing... will request a few minor changes (so far)

2023-02-16 07:26 UTC, ilyamandel requested changes
Looks great, @reinhold-willcox and @solfreludio !

I have just a few minor suggestions:

Documentation:
Do I understand correctly that DD refers specifically to a double-degenerate SNIA, while SNIA refers to all SNIA (SD or DD) when used as a SN label?  That's not obvious from the documentation -- some clarification would be useful.  

BaseBinaryStar.cpp:
I note that this comment is gone; why?  I thought it was quite useful:
// This passes through the accretor's Roche lobe radius, just in case MT_THERMALLY_LIMITED_VARIATION::RADIUS_TO_ROCHELOBE is used; otherwise, the radius input is ignored

BinaryConstituentStar::SetMassTransferDiff()
I am more comfortable with setters than @jeffriley [and this was a setter anyway] -- but now it looks like a setter, but actually calls another function, and that's not what I would expect, so I suggest at least changing this function's name.

COWD.h:
// To check the current accretion regime and mass retention. Also activates flags for type change in some situations.
Type change of what?  Maybe just "can change flag settings"?

BaseStar:
virtual double CalculateEddingtonCriticalRate()
Why is this virtual, since it's no longer over-written anywhere in an inheriting class?

2023-02-16 08:51 UTC, jeffriley requested changes
A few small points:

1. To me, "DD", and associated things like "EXPERIENCED_DD", "IS_DD", "SN_EVENT::DD", etc., isn't sufficiently descriptive.  "SNDD" probably isn't right.  What about "SNIA_DD"?

2. COWD.cpp, line 3, has the comment "/* For COWDs and ONeWDs, calculate:".  That should just be "/* For COWDs, calculate:".  The way the code is written at the moment, "/* For COWDs and ONeWDs, calculate:" is correct, because the ONeWD class doesn't implement the function.  But the function COWD::CalculateMassAcceptanceRate() does the calculation for the COWD class only.  The ONeWD class may one day implement the function, and then the comment (as is) in COWD.cpp will be wrong.

3. COWD.cpp, lines 41-49 - I think best not to enumerate the regime types here - unless you expect people to keep that comment up-to-date whenever a new regime ias added (or an existing deleted).  I think better just to refer to the ACCRETION_REGIME enum in constants.h.

4. A minute nit-pick.  The descripton of COWD::DetermineAccretionRegime() on line 39 of COWD.cpp says "Calculate the WD accretion regime", but the function is named "DetermineAccretionRegime", not "CalculateAccretionRegime".  I think "determine" is a better description of what it does.

5. You should say in the descripton of COWD::DetermineAccretionRegime() that in addition to determining the regime, it actually changes the value of a couplf of member variables (m_DoubleDetonation and m_OffCenterIgnition) - callers migts assume all it does is determine and return the regime, but in fact there are side-effects.

6. I would remove the text mentioning ONeWD in the description of COWD::ShouldEvolveOnPhase() at line 109.  The function COWD::ShouldEvolveOnPhase() simply returns a boolean flag to indicate whether the the star should continue to evolve as its current stellar type, or not - the function has no say in what the stellar type should be after it stops evolving as its current stellar type.

7. COWD::ShouldEvolveOnPhase()- rather than return from two different places (generally it is better to arrange the code so that it only exists st the end of the code - justeasier for readers to figure out what's going on if it's a long function - here doesn't matter so much because it's such a short function and the reader can easily see what's happening), why not use: return m_OffCenterIgnition ? false : !IsSupernova();  Ditto for HeWD::ShouldEvolveOnPhase().

8. This one is very minor - the current code base has the description of a function starting leaving two blank lines after the preceeding function, and there is no blank line between the description and the function declaration.  In some places you have a single line separating functions, and a blank line between the description and the declaration.  Not the end of the world, but consistency aids reeadability.

9. I think you should rewrite COWD::EvolveToNextPhase()so that it has only a single return (two is borderline, three is too many...).  Just set a variable that will be returned, and return it at the end of the function. Ditto for HeWD::EvolveToNextPhase() and ONeWD::EvolveToNextPhase()

10. WhiteDwarfs::CalculateEtaPTY() - should set a default value for etaPTY in line 96.  I know you have a covering "else" at the end, but you don't know what changes someone might make in the future, and a default value is safer.

11. In COWD::EvolveToNextPhase(), why do you have "else if (m_DoubleDetonation || IsMassAboveChandrasekhar()) {" rather than "else if(IsSupernova()) {"?  This way there is a risk that someone might change IsSupernova(), but not change the condition in COWD::EvolveToNextPhase(). Ditto for HeWD::EvolveToNextPhase() and ONeWD::EvolveToNextPhase().


Some not so minor questions/comments:

In COWD::EvolveToNextPhase(), HeWD::EvolveToNextPhase(), and ONeWD::EvolveToNextPhase() you have the following warnings (respectively):

SHOW_WARN(ERROR::WARNING, "COWD told to evolve, but not how."); // show warning
SHOW_WARN(ERROR::WARNING, "HeWD told to evolve, but not how."); // show warning
SHOW_WARN(ERROR::WARNING, "ONeWD told to evolve, but not how."); // show warning

and in each function the "SHOW_WARN" line is followed by

return ResolveAIC();


The *::EvolveToNextPhase() functions return the stellar type of the next phase for the star, and returning a valid stellar type is not negotiable - the star has to know what it is doing next - and in fact you are returning the result of the call to ResolveAIC(), which is a stellar type.  So technically the warning is not correct - except that ResolveAIC() might return the current stellar type.

I have to say the warning text bothers me...  What are you trying to convey with the warnings?  What do you expect to happen here (if those warnings are issued)?

2023-02-27 06:41 UTC, ilyamandel commented
@solfreludio and @reinhold-willcox -- if/when you've addressed the issues raised above, please send a message here tagging reviewers to say that this is ready for a final check. :-)

2023-03-09 00:27 UTC, reinhold-willcox commented
@solfreludio @ilyamandel @jeffriley 

I've gone through and addressed the remaining issues (please let me know if I missed any). 

Nicolas, Ilya's point about SD vs DD supernovae is important and one I hadn't appreciated earlier. Are SN IA's in compas implicitly referring to SD? If so, should we be more explicit about that in the variable names?

Ilya, you asked why CalculateEddingtonAccretionRate is still virtual in BaseStar since it is never overwritten, but I've left the overwriting version in BH.cpp, so we can use the BH mass to calculate the Eddington limit. Thus I believe we should leave the BaseStar function as virtual, but let me know if I misunderstood. 

Jeff, you asked about the warnings in EvolveToNextPhase in the WD classes. Right now, there is no way for the code to end up in the else clause that triggers the warnings. The purpose for the warnings is to protect against future changes that might break this functionality. The call to ResolveAIC() is just a meaningless default, and could be replaced by anything else. I am happy to do something more robust here if you prefer.

2023-03-12 21:36 UTC, jeffriley commented
I'll get to this in the next few days.

2023-03-15 22:14 UTC, jeffriley commented
@solfreludio @reinhold-willcox @ilyamandel 

I'm happy with everything **except** this:

    /*
     * Specifies next stage, if the star changes its phase.
     *
     * STELLAR_TYPE EvolveToNextPhase()
     *
     * @return                               Stellar type of the upcoming stage.
     */
    
    STELLAR_TYPE COWD::EvolveToNextPhase() {
    
        STELLAR_TYPE stellarType;

        if (m_OffCenterIgnition) {
            stellarType = STELLAR_TYPE::OXYGEN_NEON_WHITE_DWARF;
        }
        else if (IsSupernova()) {
            stellarType = ResolveSNIa(); 
        }
        else {                                         // Should not occur
            SHOW_WARN(ERROR::WARNING, "COWD told to evolve, but not how.");                                          // show warning
            stellarType = ResolveAIC();
        }
        return stellarType;
    }

First, a minor nit-pick - let's delete the blank line between the description and function declaration.

Next, the warning message should be changed to something like "Unexpected condition encountered...", and maybe put the message in ERROR_CATALOG constants.h (we don't have all error/warning messages there, but we should eventually get them all  there).

And finally, the important bit.  As @reinhold-willcox noted "The call to ResolveAIC() is just a meaningless default..." - but it's more than that in a couple of ways:

1. It's actually pointless - we know in that else clause that we are not experiencing a SN event (from the conditional just above).  The very first line of **ResolveAIC()** is 

    if (!IsSupernova()) return m_StellarType;  
    
so all calling **ResolveAIC()** will do is set stellarType = m_StellarType - we might as well do that without the call.

2. Setting stellarType = m_StellarType might have unintended consequences.  We need to know what to do next - **EvolveToNextPhase()** should indicate what stellar type the star should become.  In all other instances, except TPAGB, **EvolveToNextPhase()** changes the stellar type of the star.  (Aside: For TPAGB, **EvolveToNextPhase()** just returns the current stellar type, which I think we should look at.  I think, for TPAGB, we rely on something else changing the stellar type -e.g.  envelope loss (in **ResolveEnvelopeLoss()**) etc., but maybe we should take a closer look at that). We need to be sure that we don't inadvertently cause an endless loop here - we have successfully avoided that in COMPAS so far, and I think it is important that we continue to avoid it.

What are the consequences of not changing the stellar type here?  Will continuing to evolve with the same stellar type lead to something else happening that will change the stellar type, or are we likely to end up back in the same place, thus starting an endless loop?  We want the COMPAS run to finish, even if the evolution of this particular binary is faulty.

Should we, instead of just not changing the stellar type here and hoping things will sort themselves out, change the stellar type to (say) MR, thus forcibly terminating the evolution of the binary?  We know something is badly wrong and the results of the evolution should not be trusted, so stopping now would not be unreasonable.  We would then just go on to the next binary.  But, is MR (or whatever) the right thing to do?  This has come up before (I can't remember the context unfortunately...), and then I floated the idea that we should have a stellar type (say, "Failed Binary") to which we could switch when we identify we're in a bad place and really should just give up now and move to the next binary (we could perhaps do something similar for SSE in similar situations).  So here we would set the stellar type returned from **EvolveToNextPhase()** to (e.g.) STELLAR_TYPE::FAILED_BINARY, and write a little bit of code to ensure we stop evolving in that case (a couple of lines at most). Then users who see that stellar type in the output file will know something went wrong - and maybe that will motivate them to look at the error/warning messages.  At least then there is a positive indication in the output files that something went wrong, and they shouldn't trust the output for that binary.

2023-03-19 02:29 UTC, jeffriley commented
The easiest path forward here is to remove the offending **else** clause in whatever functions it is in, but I think the best path forward is to implement the "FAILED_BINARY" stellar type (and the corresponding SSE stellar type (maybe "FAILED_STAR").   I don't think it would take that long - a couple of days including testing - so I'd be happy to do that if everyone agrees it is the thing to do.

2023-03-20 23:50 UTC, ilyamandel commented
@jeffriley :

I like the proposed change to 

STELLAR_TYPE COWD::EvolveToNextPhase() {

    STELLAR_TYPE stellarType;

    if (m_OffCenterIgnition) {
        stellarType = STELLAR_TYPE::OXYGEN_NEON_WHITE_DWARF;
    }
    else {
        stellarType = ResolveSNIa(); 
    }
    return stellarType;
}

I realise it's not bullet-proof, but a lot of things have changed in this PR, and just looking at code won't be enough for us to diagnose all the possible issues, anyway; I think we should make the change above and then get it into dev and continue testing. :)

2023-03-20 23:50 UTC, ilyamandel commented
There are also a few conflicts to resolve.

2023-03-20 23:58 UTC, ilyamandel commented
@solfreludio : 

I still don't know the answer to this question:

Do I understand correctly that DD refers specifically to a double-degenerate SNIA, while SNIA refers to all SNIA (SD or DD) when used as a SN label? That's not obvious from the documentation -- some clarification would be useful.

@reinhold-willcox writes: Nicolas, Ilya's point about SD vs DD supernovae is important and one I hadn't appreciated earlier. Are SN IA's in compas implicitly referring to SD? If so, should we be more explicit about that in the variable names?

Can you please clarify?

2023-03-21 20:44 UTC, solfreludio commented
> @solfreludio :
> 
> I still don't know the answer to this question:
> 
> Do I understand correctly that DD refers specifically to a double-degenerate SNIA, while SNIA refers to all SNIA (SD or DD) when used as a SN label? That's not obvious from the documentation -- some clarification would be useful.
> 

DD used to refer to Double Detonation, in the context of a WD accreting helium-rich material and then experiencing a detonation in both outer and central parts of the star (hence why it is double). However, due to how easy it is to misunderstand what DD stands for, I decided to change it to "Helium Shell Detonation" (HeSD), as the event should only happen in stars accreting helium at a specific rate and forming a shell.

2023-03-21 20:56 UTC, ilyamandel commented
Thanks, @solfreludio, that makes sense!

But is it the case that the SNIA label will be applied to all type IA SNe
in COMPAS, regardless of explosion mechanism?



On Wed, 22 Mar 2023, 7:44 am Nicolas Rodriguez-Segovia, <
***@***.***> wrote:

> @solfreludio <https://github.com/solfreludio> :
>
> I still don't know the answer to this question:
>
> Do I understand correctly that DD refers specifically to a
> double-degenerate SNIA, while SNIA refers to all SNIA (SD or DD) when used
> as a SN label? That's not obvious from the documentation -- some
> clarification would be useful.
>
> DD used to refer to Double Detonation, in the context of a WD accreting
> helium-rich material and then experiencing a detonation in both outer and
> central parts of the star (hence why it is double). However, due to how
> easy it is to misunderstand what DD stands for, I decided to change it to
> "Helium Shell Detonation" (HeSD), as the event should only happen in stars
> accreting helium at a specific rate and forming a shell.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/TeamCOMPAS/COMPAS/pull/822#issuecomment-1478555380>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAD5BVJYSLH4N7E3XNKRS2LW5IHK3ANCNFSM5ZWIYU3Q>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-03-21 21:58 UTC, jeffriley commented
@ilyamandel 

> I like the proposed change to
>
> STELLAR_TYPE COWD::EvolveToNextPhase() {
> ...

I'm happy with that - but I think the change needs to be made in multiple classes (not just COWD).

Will you make the changes, or do you want me to?

2023-03-22 01:01 UTC, solfreludio commented
> Thanks, @solfreludio, that makes sense! But is it the case that the SNIA label will be applied to all type IA SNe in COMPAS, regardless of explosion mechanism?

Yes, that is right. There are no sub-classes within the SNIA label

2023-03-23 23:10 UTC, ilyamandel commented
@solfreludio -- looking at the documentation in this PR, you have the following description:

           * - SNIA
             - = 64
           * - DD
             - = 128
             
   First, there is still mention of DD here (and double detonation is mentioned elsewhere in the documentation).
   
   Secondly, I still do not understand whether, if a SNIA is labeled as "Helium Shell Detonation" (HeSD), would both the "64" and "128" bits be on, or only the "128" bit?  Can you please clarify the documentation to match the code and the text you have written above?

2023-03-23 23:12 UTC, ilyamandel commented
@jeffriley -- if you have time, can you make that change (no rush if not, I just have a few too many things to do, as usual :) )?

2023-03-23 23:13 UTC, ilyamandel commented
@solfreludio -- note that the continuing integration test is failing at the moment; this has to be fixed before this PR is approved and rolled in.

2023-03-24 01:34 UTC, solfreludio commented
> @solfreludio -- looking at the documentation in this PR, you have the following description:
> 
> ```
>        * - SNIA
>          - = 64
>        * - DD
>          - = 128
> ```
> 
> First, there is still mention of DD here (and double detonation is mentioned elsewhere in the documentation).
> 
> Secondly, I still do not understand whether, if a SNIA is labeled as "Helium Shell Detonation" (HeSD), would both the "64" and "128" bits be on, or only the "128" bit? Can you please clarify the documentation to match the code and the text you have written above?

I have updated the docs and modified the relevant `DD` mentions to be `HeSD`, as they should. Also, I think I understand why you had such confusion: there was no actual call to `ResolveHeSD` in the code and therefore the `HeSD` event was never implemented. I have added a couple of lines to `COWD.cpp` to fix this. @reinhold-willcox can you please check it?



> @solfreludio -- note that the continuing integration test is failing at the moment; this has to be fixed before this PR is approved and rolled in.

It seems there are some `<<<<<HEAD` and `>>>>>DEV` lines in `constants.h` causing the issue. I think they were introduced in @reinhold-willcox 's latest push so I will wait for his feedback (I believe this is just from the IDE).

2023-03-24 02:06 UTC, jeffriley commented
> It seems there are some <<<<<HEAD and >>>>>DEV lines in constants.h causing the issue. I think they were introduced in 
> @reinhold-willcox 's latest push so I will wait for his feedback (I believe this is just from the IDE).

<<<<<HEAD and >>>>>DEV is how git signifies conflicts that need to be resolved.  You just need at accept/reject as appropriate.

2023-03-24 15:07 UTC, reinhold-willcox commented
Fixed the else clause issue in the EvolveToNextPhase functions, and the anomalous "<<<<>>>>dev"

2023-03-24 22:00 UTC, jeffriley approved these changes
I believe all my issues have been addressed - good to go from my perspective.  Well don @solfreludio and @reinhold-willcox !

2023-03-25 01:05 UTC, ilyamandel commented
@solfreludio : Just a consideration: maybe HeSD events *should* be flagged as Type IAs at the same time?  E.g., our ultra-stripped SNe are being flagged as both USSNe and CCSNe.  This can be useful because if you want to know the total IA rate, for example, would you not include HeSDs?  Your comments certainly suggest that you think of them as a subclass of IAs (e.g., "SetSNCurrentEvent(SN_EVENT::HeSD); // SN Type Ia (HeSD) happening now".

In any case, I am happy to approve at this stage.  @reinhold-willcox -- I think you are the last missing approval. ;)

2023-03-25 01:06 UTC, ilyamandel approved these changes
Nicely done to get things to this stage! :)

2023-03-25 01:06 UTC, ilyamandel approved these changes

2023-03-26 02:04 UTC, reinhold-willcox commented
I quite like Ilya's proposed suggestion, but I would also like to get these changes merged in. I'm happy to approve and merge this in, and to create a new feature request that we can address in due time. Thanks @solfreludio for all your hard work on this!

2023-03-26 02:04 UTC, reinhold-willcox approved these changes

2023-03-26 02:04 UTC, merged