Fix for Issue #945: Make HeSD SN Type a Subclass of SNIA
TeamCOMPAS/COMPAS pull request #994
Opened 2023-09-01 12:13 UTC by LCon0032

In line with Ilya's suggestion in PR #822, this PR changes the behaviour of the SNEventType() function in the file utils.cpp to make the HeSD Supernova (SN) type a subclass of the Type Ia SNe (SNIA).

Code changed:
if ((p_SNEvent & SN_EVENT::SNIA ) == SN_EVENT::SNIA ) return SN_EVENT::SNIA;
To:
if ((p_SNEvent & (SN_EVENT::SNIA | SN_EVENT::HeSD)) == SN_EVENT::SNIA ) return SN_EVENT::SNIA;

Review issue text for details

2023-09-02 01:59 UTC, jeffriley requested changes
Thanks Lewis.  I made a couple of minor changes (fixed a typo, and made a minor formatting change - both to SNEventType() in utils.cpp).

You need to update the documentation to match - see the bottom of standard-logfiles-record-specification-stellar.rst - where SNEvenetType() is described.

2023-09-04 01:16 UTC, ilyamandel approved these changes
Hi @LCon0032 ,
Happy to approve the change as amended by @jeffriley .  :-)

2023-09-04 01:17 UTC, ilyamandel commented
> Thanks Lewis. 

It seems I am not the only one to have misspoken, Lucas! ;-)

2023-09-04 01:26 UTC, jeffriley commented
Oops.  Sorry :-)

2023-09-06 00:03 UTC, ilyamandel commented
@jeffriley -- are you looking for more changes?  If not, please approve (but don't merge -- @LCon0032 should have the honour of doing his first merge)

2023-09-06 00:16 UTC, jeffriley commented
Yes - the documentation needs to be updated.

On Wed, 6 Sept 2023, 10:03 am Ilya Mandel, ***@***.***> wrote:

> @jeffriley <https://github.com/jeffriley> -- are you looking for more
> changes? If not, please approve (but don't merge -- @LCon0032
> <https://github.com/LCon0032> should have the honour of doing his first
> merge)
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/TeamCOMPAS/COMPAS/pull/994#issuecomment-1707460423>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AGM5XNRDLBHPHC3YKDMEXT3XY64WXANCNFSM6AAAAAA4HPIV4Y>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-09-06 06:46 UTC, ilyamandel commented
But hadn't you already updated it?  It looks that way...

On Wed, 6 Sept 2023, 10:16 am jeffriley, ***@***.***> wrote:

> Yes - the documentation needs to be updated.
>
> On Wed, 6 Sept 2023, 10:03 am Ilya Mandel, ***@***.***> wrote:
>
> > @jeffriley <https://github.com/jeffriley> -- are you looking for more
> > changes? If not, please approve (but don't merge -- @LCon0032
> > <https://github.com/LCon0032> should have the honour of doing his first
> > merge)
> >
> > —
> > Reply to this email directly, view it on GitHub
> > <https://github.com/TeamCOMPAS/COMPAS/pull/994#issuecomment-1707460423>,
>
> > or unsubscribe
> > <
> https://github.com/notifications/unsubscribe-auth/AGM5XNRDLBHPHC3YKDMEXT3XY64WXANCNFSM6AAAAAA4HPIV4Y>
>
> > .
> > You are receiving this because you were mentioned.Message ID:
> > ***@***.***>
> >
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/TeamCOMPAS/COMPAS/pull/994#issuecomment-1707468768>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAD5BVK4XZAPL2XLJBODTBTXY66FRANCNFSM6AAAAAA4HPIV4Y>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2023-09-06 06:51 UTC, jeffriley commented
No.  I fixed a typo and a little bit of formatting in the code.  The online documentation here:

https://compas.readthedocs.io/en/latest/pages/User%20guide/COMPAS%20output/standard-logfiles-record-specification-stellar.html

describes SNEvenetType()  (at the bottom of the page).

As noted above, that documentation file is standard-logfiles-record-specification-stellar.rst.  The changes aren't onerous - good introduction to updating the documentation :-)

2023-09-07 00:28 UTC, ilyamandel commented
But the bottom of the page has been fixed in this PR: <img width="943" alt="image" src="https://github.com/TeamCOMPAS/COMPAS/assets/512213/b42929a4-4975-4bfb-a38c-109b8108818c">

I think you mean other text on this page, which I now realise hasn't been fixed (I was only looking at the bottom of the page, as suggested).  Anyway, agree that there are documentation things to fix, so I'll remove my approval and wait for @LCon0032 to make the relevant updates to this documentation page.

2023-09-07 00:50 UTC, jeffriley commented
@ilyamandel No, you're right - I'm just blind or something...  I did not see that the documentation had been changed (at the bottom of the page).  But, as you say, the description of SN_Type (in the same .rst file) needs to be fixed.  My apologies...

2023-09-08 03:25 UTC, LCon0032 commented
I believe I've updated the documentation as requested. Let me know if I've made any errors or missed anything.

2023-09-08 04:02 UTC, jeffriley approved these changes
Looks good - thanks Lucas.

2023-09-11 03:06 UTC, merged